// VBConversions Note: VB project level imports
using System.Data;
using System.Collections.Generic;
using PDSA.Data;
using PDSA.WinForms.Forms;
using PDSA.Security;
using System.Diagnostics;
using PDSA.Common;
using PDSA.WinForms;
using PDSA.WinForms.Security;
using PDSA.PDSACryptography;
using DoorsPOS.Utility;
using Microsoft.VisualBasic;
using System.Collections;
using System;
using DoorsPOS.BusinessLayer;
using System.Windows.Forms;
using System.Drawing;
using System.Linq;
using DoorsPOS.DataLayer;
// End of VB project level imports


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




///<summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
namespace DoorsPOS.WinApp
{
	[global::System.Serializable(), 
	global::System.ComponentModel.DesignerCategoryAttribute("code"), 
	global::System.ComponentModel.ToolboxItem(true), 
	global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"), 
	global::System.Xml.Serialization.XmlRootAttribute("dsvwDeliveries"), 
	global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]public 
	partial class dsvwDeliveries : global::System.Data.DataSet
	{
		
		private vwDlvryDetailsDataTable tablevwDlvryDetails;
		
		private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dsvwDeliveries()
		{
			this.BeginInit()();
			this.InitClass();
			global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			base.Tables.CollectionChanged += schemaChangedHandler;
			base.Relations.CollectionChanged += schemaChangedHandler;
			this.EndInit()();
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected dsvwDeliveries(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : base(info, context, false)
		{
			if (this.IsBinarySerialized(info, context) == true)
			{
				this.InitVars(false);
				global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
				this.Tables.CollectionChanged += schemaChangedHandler1;
				this.Relations.CollectionChanged += schemaChangedHandler1;
				return ;
			}
			string strSchema = System.Convert.ToString(info.GetValue("XmlSchema", typeof(string)));
			if (this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)
			{
				global::System.Data.DataSet ds = new global::System.Data.DataSet();
				ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
				if (!((ds.Tables["vwDlvryDetails"]) == null))
				{
					base.Tables.Add(new vwDlvryDetailsDataTable(ds.Tables["vwDlvryDetails"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else
			{
				this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
			}
			this.GetSerializationData(info, context);
			global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			base.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false), 
global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]public vwDlvryDetailsDataTable vwDlvryDetails
		{
			get
			{
				return this.tablevwDlvryDetails;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.BrowsableAttribute(true), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]public override global::System.Data.SchemaSerializationMode SchemaSerializationMode
		{
			get
			{
				return this._schemaSerializationMode;
			}
			set
			{
				this._schemaSerializationMode = value;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]public new global::System.Data.DataTableCollection Tables
		{
			get
			{
				return base.Tables;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]public new global::System.Data.DataRelationCollection Relations
		{
			get
			{
				return base.Relations;
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void InitializeDerivedDataSet()
		{
			this.BeginInit()();
			this.InitClass();
			this.EndInit()();
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public override global::System.Data.DataSet Clone()
		{
			dsvwDeliveries cln = (dsvwDeliveries) (base.Clone());
			cln.InitVars();
			cln.SchemaSerializationMode = this.SchemaSerializationMode;
			return cln;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override bool ShouldSerializeTables()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override bool ShouldSerializeRelations()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader)
		{
			if (this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)
			{
				this.Reset();
				global::System.Data.DataSet ds = new global::System.Data.DataSet();
				ds.ReadXml(reader);
				if (!((ds.Tables["vwDlvryDetails"]) == null))
				{
					base.Tables.Add(new vwDlvryDetailsDataTable(ds.Tables["vwDlvryDetails"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else
			{
				this.ReadXml(reader);
				this.InitVars();
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable()
		{
			global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
			this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
			stream.Position = 0;
			return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars()
		{
			this.InitVars(true);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars(bool initTable)
		{
			this.tablevwDlvryDetails = (vwDlvryDetailsDataTable) (base.Tables["vwDlvryDetails"]);
			if (initTable == true)
			{
				if (!((this.tablevwDlvryDetails) == null))
				{
					this.tablevwDlvryDetails.InitVars();
				}
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitClass()
		{
			this.DataSetName = "dsvwDeliveries";
			this.Prefix = "";
			this.Namespace = "http://tempuri.org/dsvwDeliveries.xsd";
			this.EnforceConstraints = true;
			this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
			this.tablevwDlvryDetails = new vwDlvryDetailsDataTable();
			base.Tables.Add(this.tablevwDlvryDetails);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private bool ShouldSerializevwDlvryDetails()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e)
		{
			if (e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)
			{
				this.InitVars();
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs)
		{
			dsvwDeliveries ds = new dsvwDeliveries();
			global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
			global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
			global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
			any.Namespace = ds.Namespace;
			sequence.Items.Add(any);
			type.Particle = sequence;
			global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
			if (xs.Contains(dsSchema.TargetNamespace))
			{
				global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
				global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
				try
				{
					global::System.Xml.Schema.XmlSchema schema = null;
					dsSchema.Write(s1);
					global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator();
					while (schemas.MoveNext())
					{
						schema = (global::System.Xml.Schema.XmlSchema) schemas.Current;
						s2.SetLength(0);
						schema.Write(s2);
						if (s1.Length == s2.Length)
						{
							s1.Position = 0;
							s2.Position = 0;
							
							while ((s1.Position != s1.Length) 
								&& (s1.ReadByte() == s2.ReadByte()))
							{
								
								
							}
							if (s1.Position == s1.Length)
							{
								return type;
							}
						}
						
					}
				}
				finally
				{
					if (!((s1) == null))
					{
						s1.Close();
					}
					if (!((s2) == null))
					{
						s2.Close();
					}
				}
			}
			xs.Add(dsSchema);
			return type;
		}
		
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public delegate void vwDlvryDetailsRowChangeEventHandler(object sender, vwDlvryDetailsRowChangeEvent e);
		
		///<summary>
		///Represents the strongly named DataTable class.
		///</summary>
		[global::System.Serializable(), 
		global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]public 
		partial class vwDlvryDetailsDataTable : global::System.Data.TypedTableBase<vwDlvryDetailsRow>
		{
			
			private global::System.Data.DataColumn columnstckid;
			
			private global::System.Data.DataColumn columncost;
			
			private global::System.Data.DataColumn columnqty;
			
			private global::System.Data.DataColumn columndrdetamnt;
			
			private global::System.Data.DataColumn columnfreee;
			
			private global::System.Data.DataColumn columnsInsert_id;
			
			private global::System.Data.DataColumn columndtInsert_dt;
			
			private global::System.Data.DataColumn columndrid;
			
			private global::System.Data.DataColumn columnitem_desc;
			
			private global::System.Data.DataColumn columnsupplier;
			
			private global::System.Data.DataColumn columncategoryid;
			
			private global::System.Data.DataColumn columncatgory;
			
			private global::System.Data.DataColumn columndrdscamnt;
			
			private global::System.Data.DataColumn columndrbal;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public vwDlvryDetailsDataTable()
			{
				this.TableName = "vwDlvryDetails";
				this.BeginInit()();
				this.InitClass();
				this.EndInit()();
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal vwDlvryDetailsDataTable(global::System.Data.DataTable table)
			{
				this.TableName = table.TableName;
				if (table.CaseSensitive != table.DataSet.CaseSensitive)
				{
					this.CaseSensitive = table.CaseSensitive;
				}
				if (table.Locale.ToString() != table.DataSet.Locale.ToString())
				{
					this.Locale = table.Locale;
				}
				if (table.Namespace != table.DataSet.Namespace)
				{
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected vwDlvryDetailsDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : base(info, context)
			{
				this.InitVars();
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn stckidColumn
			{
				get
				{
					return this.columnstckid;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn costColumn
			{
				get
				{
					return this.columncost;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn qtyColumn
			{
				get
				{
					return this.columnqty;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn drdetamntColumn
			{
				get
				{
					return this.columndrdetamnt;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn freeeColumn
			{
				get
				{
					return this.columnfreee;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn sInsert_idColumn
			{
				get
				{
					return this.columnsInsert_id;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn dtInsert_dtColumn
			{
				get
				{
					return this.columndtInsert_dt;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn dridColumn
			{
				get
				{
					return this.columndrid;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn item_descColumn
			{
				get
				{
					return this.columnitem_desc;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn supplierColumn
			{
				get
				{
					return this.columnsupplier;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn categoryidColumn
			{
				get
				{
					return this.columncategoryid;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn catgoryColumn
			{
				get
				{
					return this.columncatgory;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn drdscamntColumn
			{
				get
				{
					return this.columndrdscamnt;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn drbalColumn
			{
				get
				{
					return this.columndrbal;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public int Count
			{
				get
				{
					return this.Rows.Count;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public vwDlvryDetailsRow this[int index]
			{
				get
				{
					return ((vwDlvryDetailsRow) (this.Rows[index]));
				}
			}
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private vwDlvryDetailsRowChangeEventHandler vwDlvryDetailsRowChangingEvent;
			public event vwDlvryDetailsRowChangeEventHandler vwDlvryDetailsRowChanging
			{
				add
				{
					vwDlvryDetailsRowChangingEvent = (vwDlvryDetailsRowChangeEventHandler) System.Delegate.Combine(vwDlvryDetailsRowChangingEvent, value);
				}
				remove
				{
					vwDlvryDetailsRowChangingEvent = (vwDlvryDetailsRowChangeEventHandler) System.Delegate.Remove(vwDlvryDetailsRowChangingEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private vwDlvryDetailsRowChangeEventHandler vwDlvryDetailsRowChangedEvent;
			public event vwDlvryDetailsRowChangeEventHandler vwDlvryDetailsRowChanged
			{
				add
				{
					vwDlvryDetailsRowChangedEvent = (vwDlvryDetailsRowChangeEventHandler) System.Delegate.Combine(vwDlvryDetailsRowChangedEvent, value);
				}
				remove
				{
					vwDlvryDetailsRowChangedEvent = (vwDlvryDetailsRowChangeEventHandler) System.Delegate.Remove(vwDlvryDetailsRowChangedEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private vwDlvryDetailsRowChangeEventHandler vwDlvryDetailsRowDeletingEvent;
			public event vwDlvryDetailsRowChangeEventHandler vwDlvryDetailsRowDeleting
			{
				add
				{
					vwDlvryDetailsRowDeletingEvent = (vwDlvryDetailsRowChangeEventHandler) System.Delegate.Combine(vwDlvryDetailsRowDeletingEvent, value);
				}
				remove
				{
					vwDlvryDetailsRowDeletingEvent = (vwDlvryDetailsRowChangeEventHandler) System.Delegate.Remove(vwDlvryDetailsRowDeletingEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private vwDlvryDetailsRowChangeEventHandler vwDlvryDetailsRowDeletedEvent;
			public event vwDlvryDetailsRowChangeEventHandler vwDlvryDetailsRowDeleted
			{
				add
				{
					vwDlvryDetailsRowDeletedEvent = (vwDlvryDetailsRowChangeEventHandler) System.Delegate.Combine(vwDlvryDetailsRowDeletedEvent, value);
				}
				remove
				{
					vwDlvryDetailsRowDeletedEvent = (vwDlvryDetailsRowChangeEventHandler) System.Delegate.Remove(vwDlvryDetailsRowDeletedEvent, value);
				}
			}
			
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void AddvwDlvryDetailsRow(vwDlvryDetailsRow row)
			{
				this.Rows.Add(row);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public vwDlvryDetailsRow AddvwDlvryDetailsRow(int stckid, decimal cost, int qty, decimal drdetamnt, int freee, string sInsert_id, DateTime dtInsert_dt, int drid, string item_desc, string supplier, int categoryid, string catgory, decimal drdscamnt, decimal drbal)
			{
				vwDlvryDetailsRow rowvwDlvryDetailsRow = (vwDlvryDetailsRow) (this.NewRow());
				object[] columnValuesArray = new object[] {stckid, cost, qty, drdetamnt, freee, sInsert_id, dtInsert_dt, drid, item_desc, supplier, categoryid, catgory, drdscamnt, drbal};
				rowvwDlvryDetailsRow.ItemArray = columnValuesArray;
				this.Rows.Add(rowvwDlvryDetailsRow);
				return rowvwDlvryDetailsRow;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public override global::System.Data.DataTable Clone()
			{
				vwDlvryDetailsDataTable cln = (vwDlvryDetailsDataTable) (base.Clone());
				cln.InitVars();
				return cln;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Data.DataTable CreateInstance()
			{
				return new vwDlvryDetailsDataTable();
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars()
			{
				this.columnstckid = base.Columns["stckid"];
				this.columncost = base.Columns["cost"];
				this.columnqty = base.Columns["qty"];
				this.columndrdetamnt = base.Columns["drdetamnt"];
				this.columnfreee = base.Columns["freee"];
				this.columnsInsert_id = base.Columns["sInsert_id"];
				this.columndtInsert_dt = base.Columns["dtInsert_dt"];
				this.columndrid = base.Columns["drid"];
				this.columnitem_desc = base.Columns["item_desc"];
				this.columnsupplier = base.Columns["supplier"];
				this.columncategoryid = base.Columns["categoryid"];
				this.columncatgory = base.Columns["catgory"];
				this.columndrdscamnt = base.Columns["drdscamnt"];
				this.columndrbal = base.Columns["drbal"];
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitClass()
			{
				this.columnstckid = new global::System.Data.DataColumn("stckid", typeof(int), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnstckid);
				this.columncost = new global::System.Data.DataColumn("cost", typeof(decimal), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columncost);
				this.columnqty = new global::System.Data.DataColumn("qty", typeof(int), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnqty);
				this.columndrdetamnt = new global::System.Data.DataColumn("drdetamnt", typeof(decimal), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrdetamnt);
				this.columnfreee = new global::System.Data.DataColumn("freee", typeof(int), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnfreee);
				this.columnsInsert_id = new global::System.Data.DataColumn("sInsert_id", typeof(string), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnsInsert_id);
				this.columndtInsert_dt = new global::System.Data.DataColumn("dtInsert_dt", typeof(DateTime), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndtInsert_dt);
				this.columndrid = new global::System.Data.DataColumn("drid", typeof(int), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrid);
				this.columnitem_desc = new global::System.Data.DataColumn("item_desc", typeof(string), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnitem_desc);
				this.columnsupplier = new global::System.Data.DataColumn("supplier", typeof(string), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnsupplier);
				this.columncategoryid = new global::System.Data.DataColumn("categoryid", typeof(int), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columncategoryid);
				this.columncatgory = new global::System.Data.DataColumn("catgory", typeof(string), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columncatgory);
				this.columndrdscamnt = new global::System.Data.DataColumn("drdscamnt", typeof(decimal), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrdscamnt);
				this.columndrbal = new global::System.Data.DataColumn("drbal", typeof(decimal), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrbal);
				this.columnsInsert_id.MaxLength = 50;
				this.columndrid.AllowDBNull = false;
				this.columnitem_desc.AllowDBNull = false;
				this.columnitem_desc.MaxLength = 100;
				this.columnsupplier.AllowDBNull = false;
				this.columnsupplier.MaxLength = 50;
				this.columncategoryid.AllowDBNull = false;
				this.columncatgory.MaxLength = 50;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public vwDlvryDetailsRow NewvwDlvryDetailsRow()
			{
				return ((vwDlvryDetailsRow) (this.NewRow()));
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder)
			{
				return new vwDlvryDetailsRow(builder);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Type GetRowType()
			{
				return typeof(vwDlvryDetailsRow);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowChanged(e);
				if (!((this.vwDlvryDetailsRowChangedEvent) == null))
				{
					if (vwDlvryDetailsRowChangedEvent != null)
						vwDlvryDetailsRowChangedEvent(this, new vwDlvryDetailsRowChangeEvent(((vwDlvryDetailsRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowChanging(e);
				if (!((this.vwDlvryDetailsRowChangingEvent) == null))
				{
					if (vwDlvryDetailsRowChangingEvent != null)
						vwDlvryDetailsRowChangingEvent(this, new vwDlvryDetailsRowChangeEvent(((vwDlvryDetailsRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowDeleted(e);
				if (!((this.vwDlvryDetailsRowDeletedEvent) == null))
				{
					if (vwDlvryDetailsRowDeletedEvent != null)
						vwDlvryDetailsRowDeletedEvent(this, new vwDlvryDetailsRowChangeEvent(((vwDlvryDetailsRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowDeleting(e);
				if (!((this.vwDlvryDetailsRowDeletingEvent) == null))
				{
					if (vwDlvryDetailsRowDeletingEvent != null)
						vwDlvryDetailsRowDeletingEvent(this, new vwDlvryDetailsRowChangeEvent(((vwDlvryDetailsRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void RemovevwDlvryDetailsRow(vwDlvryDetailsRow row)
			{
				this.Rows.Remove(row);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs)
			{
				global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
				global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
				dsvwDeliveries ds = new dsvwDeliveries();
				global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
				any1.Namespace = "http://www.w3.org/2001/XMLSchema";
				any1.MinOccurs = new decimal(0);
				any1.MaxOccurs = decimal.MaxValue;
				any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
				sequence.Items.Add(any1);
				global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
				any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
				any2.MinOccurs = new decimal(1);
				any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
				sequence.Items.Add(any2);
				global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
				attribute1.Name = "namespace";
				attribute1.FixedValue = ds.Namespace;
				type.Attributes.Add(attribute1);
				global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
				attribute2.Name = "tableTypeName";
				attribute2.FixedValue = "vwDlvryDetailsDataTable";
				type.Attributes.Add(attribute2);
				type.Particle = sequence;
				global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
				if (xs.Contains(dsSchema.TargetNamespace))
				{
					global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
					global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
					try
					{
						global::System.Xml.Schema.XmlSchema schema = null;
						dsSchema.Write(s1);
						global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator();
						while (schemas.MoveNext())
						{
							schema = (global::System.Xml.Schema.XmlSchema) schemas.Current;
							s2.SetLength(0);
							schema.Write(s2);
							if (s1.Length == s2.Length)
							{
								s1.Position = 0;
								s2.Position = 0;
								
								while ((s1.Position != s1.Length) 
									&& (s1.ReadByte() == s2.ReadByte()))
								{
									
									
								}
								if (s1.Position == s1.Length)
								{
									return type;
								}
							}
							
						}
					}
					finally
					{
						if (!((s1) == null))
						{
							s1.Close();
						}
						if (!((s2) == null))
						{
							s2.Close();
						}
					}
				}
				xs.Add(dsSchema);
				return type;
			}
		}
		
		///<summary>
		///Represents strongly named DataRow class.
		///</summary>
		public partial class vwDlvryDetailsRow : global::System.Data.DataRow
		{
			
			private vwDlvryDetailsDataTable tablevwDlvryDetails;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal vwDlvryDetailsRow(global::System.Data.DataRowBuilder rb) : base(rb)
			{
				this.tablevwDlvryDetails = (vwDlvryDetailsDataTable) this.Table;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int stckid
			{
				get
				{
					try
					{
						return System.Convert.ToInt32(this[this.tablevwDlvryDetails.stckidColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'stckid\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.stckidColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public decimal cost
			{
				get
				{
					try
					{
						return System.Convert.ToDecimal(this[this.tablevwDlvryDetails.costColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'cost\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.costColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int qty
			{
				get
				{
					try
					{
						return System.Convert.ToInt32(this[this.tablevwDlvryDetails.qtyColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'qty\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.qtyColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public decimal drdetamnt
			{
				get
				{
					try
					{
						return System.Convert.ToDecimal(this[this.tablevwDlvryDetails.drdetamntColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'drdetamnt\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.drdetamntColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int freee
			{
				get
				{
					try
					{
						return System.Convert.ToInt32(this[this.tablevwDlvryDetails.freeeColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'freee\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.freeeColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public string sInsert_id
			{
				get
				{
					try
					{
						return System.Convert.ToString(this[this.tablevwDlvryDetails.sInsert_idColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'sInsert_id\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.sInsert_idColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public DateTime dtInsert_dt
			{
				get
				{
					try
					{
						return System.Convert.ToDateTime(this[this.tablevwDlvryDetails.dtInsert_dtColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'dtInsert_dt\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.dtInsert_dtColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int drid
			{
				get
				{
					return System.Convert.ToInt32(this[this.tablevwDlvryDetails.dridColumn]);
				}
				set
				{
					this[this.tablevwDlvryDetails.dridColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public string item_desc
			{
				get
				{
					return System.Convert.ToString(this[this.tablevwDlvryDetails.item_descColumn]);
				}
				set
				{
					this[this.tablevwDlvryDetails.item_descColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public string supplier
			{
				get
				{
					return System.Convert.ToString(this[this.tablevwDlvryDetails.supplierColumn]);
				}
				set
				{
					this[this.tablevwDlvryDetails.supplierColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int categoryid
			{
				get
				{
					return System.Convert.ToInt32(this[this.tablevwDlvryDetails.categoryidColumn]);
				}
				set
				{
					this[this.tablevwDlvryDetails.categoryidColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public string catgory
			{
				get
				{
					try
					{
						return System.Convert.ToString(this[this.tablevwDlvryDetails.catgoryColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'catgory\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.catgoryColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public decimal drdscamnt
			{
				get
				{
					try
					{
						return System.Convert.ToDecimal(this[this.tablevwDlvryDetails.drdscamntColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'drdscamnt\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.drdscamntColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public decimal drbal
			{
				get
				{
					try
					{
						return System.Convert.ToDecimal(this[this.tablevwDlvryDetails.drbalColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'drbal\' in table \'vwDlvryDetails\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablevwDlvryDetails.drbalColumn] = value;
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsstckidNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.stckidColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetstckidNull()
			{
				this[this.tablevwDlvryDetails.stckidColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IscostNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.costColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetcostNull()
			{
				this[this.tablevwDlvryDetails.costColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsqtyNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.qtyColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetqtyNull()
			{
				this[this.tablevwDlvryDetails.qtyColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsdrdetamntNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.drdetamntColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetdrdetamntNull()
			{
				this[this.tablevwDlvryDetails.drdetamntColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsfreeeNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.freeeColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetfreeeNull()
			{
				this[this.tablevwDlvryDetails.freeeColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IssInsert_idNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.sInsert_idColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetsInsert_idNull()
			{
				this[this.tablevwDlvryDetails.sInsert_idColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsdtInsert_dtNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.dtInsert_dtColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetdtInsert_dtNull()
			{
				this[this.tablevwDlvryDetails.dtInsert_dtColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IscatgoryNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.catgoryColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetcatgoryNull()
			{
				this[this.tablevwDlvryDetails.catgoryColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsdrdscamntNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.drdscamntColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetdrdscamntNull()
			{
				this[this.tablevwDlvryDetails.drdscamntColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsdrbalNull()
			{
				return this.IsNull(this.tablevwDlvryDetails.drbalColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetdrbalNull()
			{
				this[this.tablevwDlvryDetails.drbalColumn] = global::System.Convert.DBNull;
			}
		}
		
		///<summary>
		///Row event argument class
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public class vwDlvryDetailsRowChangeEvent : global::System.EventArgs
		{
			
			private vwDlvryDetailsRow eventRow;
			
			private global::System.Data.DataRowAction eventAction;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public vwDlvryDetailsRowChangeEvent(vwDlvryDetailsRow row, global::System.Data.DataRowAction action)
			{
				this.eventRow = row;
				this.eventAction = action;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public vwDlvryDetailsRow Row
			{
				get
				{
					return this.eventRow;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataRowAction Action
			{
				get
				{
					return this.eventAction;
				}
			}
		}
	}
	
	namespace dsvwDeliveriesTableAdapters
	{
		
		///<summary>
		///Represents the connection and commands used to retrieve and save data.
		///</summary>
		[global::System.ComponentModel.DesignerCategoryAttribute("code"), 
		global::System.ComponentModel.ToolboxItem(true), 
		global::System.ComponentModel.DataObjectAttribute(true), 
		global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" + 
		", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"), 
		global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]public 
		partial class vwDlvryDetailsTableAdapter : global::System.ComponentModel.Component
		{
			
			private global::System.Data.SqlClient.SqlDataAdapter _adapter;
			
			private global::System.Data.SqlClient.SqlConnection _connection;
			
			private global::System.Data.SqlClient.SqlTransaction _transaction;
			
			private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
			
			private bool _clearBeforeFill;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public vwDlvryDetailsTableAdapter()
			{
				this.ClearBeforeFill = true;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected internal global::System.Data.SqlClient.SqlDataAdapter Adapter
			{
				get
				{
					if (this._adapter == null)
					{
						this.InitAdapter();
					}
					return this._adapter;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal global::System.Data.SqlClient.SqlConnection Connection
			{
				get
				{
					if (this._connection == null)
					{
						this.InitConnection();
					}
					return this._connection;
				}
				set
				{
					this._connection = value;
					if (!((this.Adapter.InsertCommand) == null))
					{
						this.Adapter.InsertCommand.Connection = value;
					}
					if (!((this.Adapter.DeleteCommand) == null))
					{
						this.Adapter.DeleteCommand.Connection = value;
					}
					if (!((this.Adapter.UpdateCommand) == null))
					{
						this.Adapter.UpdateCommand.Connection = value;
					}
					int i = 0;
					while (i < this.CommandCollection.Length)
					{
						if (!((this.CommandCollection[i]) == null))
						{
							((global::System.Data.SqlClient.SqlCommand) (this.CommandCollection[i])).Connection = value;
						}
						i = i + 1;
					}
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal global::System.Data.SqlClient.SqlTransaction Transaction
			{
				get
				{
					return this._transaction;
				}
				set
				{
					this._transaction = value;
					int i = 0;
					while (i < this.CommandCollection.Length)
					{
						this.CommandCollection[i].Transaction = this._transaction;
						i = i + 1;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.DeleteCommand) == null)))
					{
						this.Adapter.DeleteCommand.Transaction = this._transaction;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.InsertCommand) == null)))
					{
						this.Adapter.InsertCommand.Transaction = this._transaction;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.UpdateCommand) == null)))
					{
						this.Adapter.UpdateCommand.Transaction = this._transaction;
					}
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected global::System.Data.SqlClient.SqlCommand[] CommandCollection
			{
				get
				{
					if (this._commandCollection == null)
					{
						this.InitCommandCollection();
					}
					return this._commandCollection;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool ClearBeforeFill
			{
				get
				{
					return this._clearBeforeFill;
				}
				set
				{
					this._clearBeforeFill = value;
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitAdapter()
			{
				this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
				global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
				tableMapping.SourceTable = "Table";
				tableMapping.DataSetTable = "vwDlvryDetails";
				tableMapping.ColumnMappings.Add("stckid", "stckid");
				tableMapping.ColumnMappings.Add("cost", "cost");
				tableMapping.ColumnMappings.Add("qty", "qty");
				tableMapping.ColumnMappings.Add("drdetamnt", "drdetamnt");
				tableMapping.ColumnMappings.Add("freee", "freee");
				tableMapping.ColumnMappings.Add("sInsert_id", "sInsert_id");
				tableMapping.ColumnMappings.Add("dtInsert_dt", "dtInsert_dt");
				tableMapping.ColumnMappings.Add("drid", "drid");
				tableMapping.ColumnMappings.Add("item_desc", "item_desc");
				tableMapping.ColumnMappings.Add("supplier", "supplier");
				tableMapping.ColumnMappings.Add("categoryid", "categoryid");
				tableMapping.ColumnMappings.Add("catgory", "catgory");
				tableMapping.ColumnMappings.Add("drdscamnt", "drdscamnt");
				tableMapping.ColumnMappings.Add("drbal", "drbal");
				this._adapter.TableMappings.Add(tableMapping);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitConnection()
			{
				this._connection = new global::System.Data.SqlClient.SqlConnection();
				this._connection.ConnectionString = global::DoorsPOS.WinApp.My.Settings.Default.doorsposConnectionString;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitCommandCollection()
			{
				this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
				this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
				this._commandCollection[0].Connection = this.Connection;
				this._commandCollection[0].CommandText = "SELECT     stckid, cost, qty, drdetamnt, freee, sInsert_id, dtInsert_dt, drid, it" + 
					"em_desc, supplier, categoryid, catgory, drdscamnt, drbal" + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(13)) + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(10)) + "FROM         vwDlvryDe" + 
					"tails";
				this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
			global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"), 
			global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]public virtual int Fill(dsvwDeliveries.vwDlvryDetailsDataTable dataTable)
			{
				this.Adapter.SelectCommand = this.CommandCollection[0];
				if (this.ClearBeforeFill == true)
				{
					dataTable.Clear();
				}
				int returnValue = this.Adapter.Fill(dataTable);
				return returnValue;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
			global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"), 
			global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]public virtual dsvwDeliveries.vwDlvryDetailsDataTable GetData()
			{
				this.Adapter.SelectCommand = this.CommandCollection[0];
				dsvwDeliveries.vwDlvryDetailsDataTable dataTable = new dsvwDeliveries.vwDlvryDetailsDataTable();
				this.Adapter.Fill(dataTable);
				return dataTable;
			}
		}
		
		///<summary>
		///TableAdapterManager is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios
		///</summary>
		[global::System.ComponentModel.DesignerCategoryAttribute("code"), 
		global::System.ComponentModel.ToolboxItem(true), 
		global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterManagerDesigner, Microsoft.VSD" + 
		"esigner, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"), 
		global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapterManager")]public 
		partial class TableAdapterManager : global::System.ComponentModel.Component
		{
			
			private UpdateOrderOption _updateOrder;
			
			private bool _backupDataSetBeforeUpdate;
			
			private global::System.Data.IDbConnection _connection;
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public UpdateOrderOption UpdateOrder
			{
				get
				{
					return this._updateOrder;
				}
				set
				{
					this._updateOrder = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool BackupDataSetBeforeUpdate
			{
				get
				{
					return this._backupDataSetBeforeUpdate;
				}
				set
				{
					this._backupDataSetBeforeUpdate = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public global::System.Data.IDbConnection Connection
			{
				get
				{
					if (!((this._connection) == null))
					{
						return this._connection;
					}
					return null;
				}
				set
				{
					this._connection = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public int TableAdapterInstanceCount
			{
				get
				{
					int count = 0;
					return count;
				}
			}
			
			///<summary>
			///Update rows in top-down order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateUpdatedRows(dsvwDeliveries dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Insert rows in top-down order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateInsertedRows(dsvwDeliveries dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Delete rows in bottom-up order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateDeletedRows(dsvwDeliveries dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Remove inserted rows that become updated rows after calling TableAdapter.Update(inserted rows) first
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private global::System.Data.DataRow[] GetRealUpdatedRows(global::System.Data.DataRow[] updatedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				if ((updatedRows == null) 
					|| (updatedRows.Length < 1))
				{
					return updatedRows;
				}
				if ((allAddedRows == null) 
					|| (allAddedRows.Count < 1))
				{
					return updatedRows;
				}
				global::System.Collections.Generic.List<global::System.Data.DataRow> realUpdatedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				int i = 0;
				while (i < updatedRows.Length)
				{
					global::System.Data.DataRow row = updatedRows[i];
					if (allAddedRows.Contains(row) == false)
					{
						realUpdatedRows.Add(row);
					}
					i = i + 1;
				}
				return realUpdatedRows.ToArray;
			}
			
			///<summary>
			///Update all changes to the dataset.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public virtual int UpdateAll(dsvwDeliveries dataSet)
			{
				if (dataSet == null)
				{
					throw (new global::System.ArgumentNullException("dataSet"));
				}
				if (dataSet.HasChanges() == false)
				{
					return 0;
				}
				global::System.Data.IDbConnection workConnection = this.Connection;
				if (workConnection == null)
				{
					throw (new global::System.ApplicationException("TableAdapterManager contains no connection information. Set each TableAdapterMana" + 
						"ger TableAdapter property to a valid TableAdapter instance."));
				}
				bool workConnOpened = false;
				if ((workConnection.State & global::System.Data.ConnectionState.Broken) 
					== (int) global::System.Data.ConnectionState.Broken)
				{
					workConnection.Close();
				}
				if (workConnection.State == global::System.Data.ConnectionState.Closed)
				{
					workConnection.Open();
					workConnOpened = true;
				}
				global::System.Data.IDbTransaction workTransaction = workConnection.BeginTransaction();
				if (workTransaction == null)
				{
					throw (new global::System.ApplicationException("The transaction cannot begin. The current data connection does not support transa" + 
						"ctions or the current state is not allowing the transaction to begin."));
				}
				global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter> adaptersWithAcceptChangesDuringUpdate = new global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter>();
				global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection> revertConnections = new global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection>();
				int result = 0;
				global::System.Data.DataSet backupDataSet = null;
				if (this.BackupDataSetBeforeUpdate)
				{
					backupDataSet = new global::System.Data.DataSet();
					backupDataSet.Merge(dataSet);
				}
				try
				{
					//---- Prepare for update -----------
					//
					//
					//---- Perform updates -----------
					//
					if (this.UpdateOrder == UpdateOrderOption.UpdateInsertDelete)
					{
						result = result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows);
						result = result + this.UpdateInsertedRows(dataSet, allAddedRows);
					}
					else
					{
						result = result + this.UpdateInsertedRows(dataSet, allAddedRows);
						result = result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows);
					}
					result = result + this.UpdateDeletedRows(dataSet, allChangedRows);
					//
					//---- Commit updates -----------
					//
					workTransaction.Commit();
					if (0 < allAddedRows.Count)
					{
						global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allAddedRows.Count) - 1 + 1];
						allAddedRows.CopyTo(rows);
						int i = 0;
						while (i < rows.Length)
						{
							global::System.Data.DataRow row = rows[i];
							row.AcceptChanges();
							i = i + 1;
						}
					}
					if (0 < allChangedRows.Count)
					{
						global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allChangedRows.Count) - 1 + 1];
						allChangedRows.CopyTo(rows);
						int i = 0;
						while (i < rows.Length)
						{
							global::System.Data.DataRow row = rows[i];
							row.AcceptChanges();
							i = i + 1;
						}
					}
				}
				catch (global::System.Exception ex)
				{
					workTransaction.Rollback();
					//---- Restore the dataset -----------
					if (this.BackupDataSetBeforeUpdate)
					{
						global::System.Diagnostics.Debug.Assert(!((backupDataSet) == null));
						dataSet.Clear();
						dataSet.Merge(backupDataSet);
					}
					else
					{
						if (0 < allAddedRows.Count)
						{
							global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allAddedRows.Count) - 1 + 1];
							allAddedRows.CopyTo(rows);
							int i = 0;
							while (i < rows.Length)
							{
								global::System.Data.DataRow row = rows[i];
								row.AcceptChanges();
								row.SetAdded();
								i = i + 1;
							}
						}
					}
					throw (ex);
				}
				finally
				{
					if (workConnOpened)
					{
						workConnection.Close();
					}
					if (0 < adaptersWithAcceptChangesDuringUpdate.Count)
					{
						global::System.Data.Common.DataAdapter[] adapters = new global::System.Data.Common.DataAdapter[(adaptersWithAcceptChangesDuringUpdate.Count) - 1 + 1];
						adaptersWithAcceptChangesDuringUpdate.CopyTo(adapters);
						int i = 0;
						while (i < adapters.Length)
						{
							global::System.Data.Common.DataAdapter adapter = adapters[i];
							adapter.AcceptChangesDuringUpdate = true;
							i = i + 1;
						}
					}
				}
				return result;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected virtual void SortSelfReferenceRows(global::System.Data.DataRow[] rows, global::System.Data.DataRelation relation, bool childFirst)
			{
				global::System.Array.Sort<global::System.Data.DataRow>(rows, new SelfReferenceComparer(relation, childFirst));
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected virtual bool MatchTableAdapterConnection(global::System.Data.IDbConnection inputConnection)
			{
				if (!((this._connection) == null))
				{
					return true;
				}
				if ((this.Connection == null) 
					|| (inputConnection == null))
				{
					return true;
				}
				if (string.Equals(this.Connection.ConnectionString, inputConnection.ConnectionString, global::System.StringComparison.Ordinal))
				{
					return true;
				}
				return false;
			}
			
			///<summary>
			///Update Order Option
			///</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public enum UpdateOrderOption
			{
				
				InsertUpdateDelete = 0,
				
				UpdateInsertDelete = 1
			}
			
			///<summary>
			///Used to sort self-referenced table's rows
			///</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private class SelfReferenceComparer : object, global::System.Collections.Generic.IComparer<global::System.Data.DataRow>
			{
				
				private global::System.Data.DataRelation _relation;
				
				private int _childFirst;
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal SelfReferenceComparer(global::System.Data.DataRelation relation, bool childFirst)
				{
					this._relation = relation;
					if (childFirst)
					{
						this._childFirst = -1;
					}
					else
					{
						this._childFirst = 1;
					}
				}
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private global::System.Data.DataRow GetRoot(global::System.Data.DataRow row, ref int distance)
				{
					global::System.Diagnostics.Debug.Assert(!((row) == null));
					global::System.Data.DataRow root = row;
					distance = 0;
					
					global::System.Collections.Generic.IDictionary<global::System.Data.DataRow, global::System.Data.DataRow> traversedRows = new global::System.Collections.Generic.Dictionary<global::System.Data.DataRow, global::System.Data.DataRow>();
					traversedRows[row] = row;
					
					global::System.Data.DataRow parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
					
					while ((!((parent) == null)) 
						&& (traversedRows.ContainsKey(parent) == false))
					{
						distance = distance + 1;
						root = parent;
						traversedRows[parent] = parent;
						parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
						
					}
					
					if (distance == 0)
					{
						traversedRows.Clear();
						traversedRows[row] = row;
						parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
						
						while ((!((parent) == null)) 
							&& (traversedRows.ContainsKey(parent) == false))
						{
							distance = distance + 1;
							root = parent;
							traversedRows[parent] = parent;
							parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
							
						}
					}
					
					return root;
				}
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int Compare(global::System.Data.DataRow row1, global::System.Data.DataRow row2)
				{
					if (object.ReferenceEquals(row1, row2))
					{
						return 0;
					}
					if (row1 == null)
					{
						return -1;
					}
					if (row2 == null)
					{
						return 1;
					}
					
					int distance1 = 0;
					global::System.Data.DataRow root1 = this.GetRoot(row1, ref distance1);
					
					int distance2 = 0;
					global::System.Data.DataRow root2 = this.GetRoot(row2, ref distance2);
					
					if (object.ReferenceEquals(root1, root2))
					{
						return (this._childFirst * distance1.CompareTo(distance2));
					}
					else
					{
						global::System.Diagnostics.Debug.Assert((!((root1.Table) == null)) 
							&& (!((root2.Table) == null)));
						if (root1.Table.Rows.IndexOf(root1) < root2.Table.Rows.IndexOf(root2))
						{
							return -1;
						}
						else
						{
							return 1;
						}
					}
				}
			}
		}
	}
	
}
