Imports PDSA.DataLayer.DataClasses

Public Class frmIssueChk
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        BankTableAdapter1.Fill(DsBank1.bank)
    End Sub

    Private Sub btnSave_Click(sender As Object, e As EventArgs) Handles btnSave.Click
        If ceBegCash.Value <= 0 Then
            MessageBox.Show("Invalid Amount")
        End If

        If ceChequeNo.Value <= 0 Then
            MessageBox.Show("Invalid Cheque No.")
        End If

        If txtPayee.Text = "" Then
            MessageBox.Show("Payee must not be empty")
        End If

        Try
            Dim tran As PDSATransaction
            tran = New PDSATransaction()
            Dim rmmgr As ChkIssuedManager = New ChkIssuedManager()
            rmmgr.DataObject.TransactionType = PDSATransactionType.Insert
            rmmgr.Entity.bankid = CInt(LookUpEdit1.EditValue)
            rmmgr.Entity.Chkdate = CDate(deDate.EditValue)
            rmmgr.Entity.Chkno = CStr(ceChequeNo.Value)
            rmmgr.Entity.ChkAmnt = CDec(ceBegCash.Value)
            rmmgr.Entity.Payee = txtPayee.Text
            rmmgr.Entity.Remarks = txtRemarks.Text
            rmmgr.Entity.sInsertid = PDSAAppConfig.CurrentLoginID
            rmmgr.Entity.dtInsertdt = DateTime.Now
            rmmgr.Entity.sLastUpdatedt = DateTime.Now
            tran.Add(rmmgr.DataObject)
            tran.Execute()
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try

    End Sub

    Private Sub frmIssueChk_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ceChequeNo.Value = 0
        ceBegCash.Value = 0
        LookUpEdit1.Focus()
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        ceChequeNo.Value = 0
        txtPayee.Text = ""
        txtRemarks.Text = ""
        ceBegCash.Value = 0
        LookUpEdit1.Focus()
    End Sub
End Class