Public Class frmIncentiveGrid

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' VwIncentivesTableAdapter1.Fill(DsIncentives1.vwIncentives)
        DevExpress.Utils.AppearanceObject.DefaultFont = New Font("Courier New", 12)
    End Sub

    Private Sub GridControl1_DoubleClick(sender As Object, e As EventArgs) Handles GridControl1.DoubleClick
        GridControl1.ShowPrintPreview()
    End Sub

    Private Sub frmIncentiveGrid_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'DsSpIncentive.spIncentive' table. You can move, or remove it, as needed.
        Me.SpIncentiveTableAdapter.Fill(Me.DsSpIncentive.spIncentive)

    End Sub
End Class