Public Class frmEmployee

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        WaitersTableAdapter1.Fill(DsEmployees1.waiters)
    End Sub

    Private Sub simBtnSave_Click(sender As Object, e As EventArgs) Handles simBtnSave.Click
        Try
            c1DataViewSet1.Update()
            MessageBox.Show("Changes Saved", "DoorsPOS")
        Catch ex As Exception
            MessageBox.Show("Not Saved, Password too weak!")
        End Try

    End Sub

    Private Sub frmEmployee_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub
End Class