Public Class ClassStock
    Public Property stckid As Integer
    Public Property barcode As String
    Public Property item_desc As String
    Public Property available As Double?
    Public Property pckgqty As Double?
    Public Property packaging As Double?
    Public Property supcode As Integer?
    Public Property categoryid As Integer?
    Public Property beginvstock As Decimal?
    Public Property dept As Integer?
    Public Property pckg_cost As Decimal?
    Public Property cost As Decimal?
    Public Property retail As Decimal?
    Public Property wsale As Decimal?
    Public Property markup As Double?
    Public Property markup2 As Double?
    Public Property retail2 As Decimal?
    Public Property minimum As Double?
    Public Property lastprice As Decimal?
    Public Property lastdlvry As DateTime?
    Public Property maximum As Double?
    Public Property sravlbl As Double?
    Public Property srpckqty As Double?
    Public Property sr_dlvry As Double?
    Public Property sizeid As Integer?
    Public Property sInsert_id As String
    Public Property dtInsert_dt As DateTime?
    Public Property sLastUpdate_id As String
    Public Property dtLastUpdate_dt As DateTime?
    Public Property iConcurrency_id As Short?
    Public Property lastcost As Decimal?
    Public Property lastwholesale As Decimal?
    Public Property incentive As Decimal?
    Public Property active As Boolean?
    Public Property VAT As Integer?
    Public Property markup3 As Double?
    Public Property markup4 As Double?
    Public Property markup5 As Double?
    Public Property retail3 As Decimal?
    Public Property retail4 As Decimal?
    Public Property retail5 As Decimal?
    Public Property retail6 As Decimal?
    Public Property retail7 As Decimal?
    Public Property retail8 As Decimal?
    Public Property retail9 As Decimal?
    Public Property retail10 As Decimal?
End Class
