// VBConversions Note: VB project level imports
using System.Data;
using System.Collections.Generic;
using PDSA.Data;
using PDSA.WinForms.Forms;
using PDSA.Security;
using System.Diagnostics;
using PDSA.Common;
using PDSA.WinForms;
using PDSA.WinForms.Security;
using PDSA.PDSACryptography;
using DoorsPOS.Utility;
using Microsoft.VisualBasic;
using System.Collections;
using System;
using DoorsPOS.BusinessLayer;
using System.Windows.Forms;
using System.Drawing;
using System.Linq;
using DoorsPOS.DataLayer;
// End of VB project level imports


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




///<summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
namespace DoorsPOS.WinApp
{
	[global::System.Serializable(), 
	global::System.ComponentModel.DesignerCategoryAttribute("code"), 
	global::System.ComponentModel.ToolboxItem(true), 
	global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"), 
	global::System.Xml.Serialization.XmlRootAttribute("dsItemCostRetail"), 
	global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]public 
	partial class dsItemCostRetail : global::System.Data.DataSet
	{
		
		private stocksDataTable tablestocks;
		
		private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dsItemCostRetail()
		{
			this.BeginInit();
			this.InitClass();
			global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			base.Tables.CollectionChanged += schemaChangedHandler;
			base.Relations.CollectionChanged += schemaChangedHandler;
			this.EndInit();
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected dsItemCostRetail(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : base(info, context, false)
		{
			if (this.IsBinarySerialized(info, context) == true)
			{
				this.InitVars(false);
				global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
				this.Tables.CollectionChanged += schemaChangedHandler1;
				this.Relations.CollectionChanged += schemaChangedHandler1;
				return ;
			}
			string strSchema = System.Convert.ToString(info.GetValue("XmlSchema", typeof(string)));
			if (this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)
			{
				global::System.Data.DataSet ds = new global::System.Data.DataSet();
				ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
				if (!((ds.Tables["stocks"]) == null))
				{
					base.Tables.Add(new stocksDataTable(ds.Tables["stocks"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else
			{
				this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
			}
			this.GetSerializationData(info, context);
			global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			base.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false), 
global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]public stocksDataTable stocks
		{
			get
			{
				return this.tablestocks;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.BrowsableAttribute(true), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]public override global::System.Data.SchemaSerializationMode SchemaSerializationMode
		{
			get
			{
				return this._schemaSerializationMode;
			}
			set
			{
				this._schemaSerializationMode = value;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]public new global::System.Data.DataTableCollection Tables
		{
			get
			{
				return base.Tables;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]public new global::System.Data.DataRelationCollection Relations
		{
			get
			{
				return base.Relations;
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void InitializeDerivedDataSet()
		{
			this.BeginInit();
			this.InitClass();
			this.EndInit();
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public override global::System.Data.DataSet Clone()
		{
			dsItemCostRetail cln = (dsItemCostRetail) (base.Clone());
			cln.InitVars();
			cln.SchemaSerializationMode = this.SchemaSerializationMode;
			return cln;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override bool ShouldSerializeTables()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override bool ShouldSerializeRelations()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader)
		{
			if (this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)
			{
				this.Reset();
				global::System.Data.DataSet ds = new global::System.Data.DataSet();
				ds.ReadXml(reader);
				if (!((ds.Tables["stocks"]) == null))
				{
					base.Tables.Add(new stocksDataTable(ds.Tables["stocks"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else
			{
				this.ReadXml(reader);
				this.InitVars();
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable()
		{
			global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
			this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
			stream.Position = 0;
			return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars()
		{
			this.InitVars(true);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars(bool initTable)
		{
			this.tablestocks = (stocksDataTable) (base.Tables["stocks"]);
			if (initTable == true)
			{
				if (!((this.tablestocks) == null))
				{
					this.tablestocks.InitVars();
				}
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitClass()
		{
			this.DataSetName = "dsItemCostRetail";
			this.Prefix = "";
			this.Namespace = "http://tempuri.org/dsItemCostRetail.xsd";
			this.EnforceConstraints = true;
			this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
			this.tablestocks = new stocksDataTable();
			base.Tables.Add(this.tablestocks);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private bool ShouldSerializestocks()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e)
		{
			if (e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)
			{
				this.InitVars();
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs)
		{
			dsItemCostRetail ds = new dsItemCostRetail();
			global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
			global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
			global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
			any.Namespace = ds.Namespace;
			sequence.Items.Add(any);
			type.Particle = sequence;
			global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
			if (xs.Contains(dsSchema.TargetNamespace))
			{
				global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
				global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
				try
				{
					global::System.Xml.Schema.XmlSchema schema = null;
					dsSchema.Write(s1);
					global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator();
					while (schemas.MoveNext())
					{
						schema = (global::System.Xml.Schema.XmlSchema) schemas.Current;
						s2.SetLength(0);
						schema.Write(s2);
						if (s1.Length == s2.Length)
						{
							s1.Position = 0;
							s2.Position = 0;
							
							while ((s1.Position != s1.Length) 
								&& (s1.ReadByte() == s2.ReadByte()))
							{
								
								
							}
							if (s1.Position == s1.Length)
							{
								return type;
							}
						}
						
					}
				}
				finally
				{
					if (!((s1) == null))
					{
						s1.Close();
					}
					if (!((s2) == null))
					{
						s2.Close();
					}
				}
			}
			xs.Add(dsSchema);
			return type;
		}
		
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public delegate void stocksRowChangeEventHandler(object sender, stocksRowChangeEvent e);
		
		///<summary>
		///Represents the strongly named DataTable class.
		///</summary>
		[global::System.Serializable(), 
		global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]public 
		partial class stocksDataTable : global::System.Data.TypedTableBase<stocksRow>
		{
			
			private global::System.Data.DataColumn columnitem_desc;
			
			private global::System.Data.DataColumn columnavailable;
			
			private global::System.Data.DataColumn columncost;
			
			private global::System.Data.DataColumn columnretail;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public stocksDataTable()
			{
				this.TableName = "stocks";
				this.BeginInit();
				this.InitClass();
				this.EndInit();
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal stocksDataTable(global::System.Data.DataTable table)
			{
				this.TableName = table.TableName;
				if (table.CaseSensitive != table.DataSet.CaseSensitive)
				{
					this.CaseSensitive = table.CaseSensitive;
				}
				if (table.Locale.ToString() != table.DataSet.Locale.ToString())
				{
					this.Locale = table.Locale;
				}
				if (table.Namespace != table.DataSet.Namespace)
				{
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected stocksDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : base(info, context)
			{
				this.InitVars();
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn item_descColumn
			{
				get
				{
					return this.columnitem_desc;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn availableColumn
			{
				get
				{
					return this.columnavailable;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn costColumn
			{
				get
				{
					return this.columncost;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn retailColumn
			{
				get
				{
					return this.columnretail;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public int Count
			{
				get
				{
					return this.Rows.Count;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public stocksRow this[int index]
			{
				get
				{
					return ((stocksRow) (this.Rows[index]));
				}
			}
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private stocksRowChangeEventHandler stocksRowChangingEvent;
			public event stocksRowChangeEventHandler stocksRowChanging
			{
				add
				{
					stocksRowChangingEvent = (stocksRowChangeEventHandler) System.Delegate.Combine(stocksRowChangingEvent, value);
				}
				remove
				{
					stocksRowChangingEvent = (stocksRowChangeEventHandler) System.Delegate.Remove(stocksRowChangingEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private stocksRowChangeEventHandler stocksRowChangedEvent;
			public event stocksRowChangeEventHandler stocksRowChanged
			{
				add
				{
					stocksRowChangedEvent = (stocksRowChangeEventHandler) System.Delegate.Combine(stocksRowChangedEvent, value);
				}
				remove
				{
					stocksRowChangedEvent = (stocksRowChangeEventHandler) System.Delegate.Remove(stocksRowChangedEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private stocksRowChangeEventHandler stocksRowDeletingEvent;
			public event stocksRowChangeEventHandler stocksRowDeleting
			{
				add
				{
					stocksRowDeletingEvent = (stocksRowChangeEventHandler) System.Delegate.Combine(stocksRowDeletingEvent, value);
				}
				remove
				{
					stocksRowDeletingEvent = (stocksRowChangeEventHandler) System.Delegate.Remove(stocksRowDeletingEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private stocksRowChangeEventHandler stocksRowDeletedEvent;
			public event stocksRowChangeEventHandler stocksRowDeleted
			{
				add
				{
					stocksRowDeletedEvent = (stocksRowChangeEventHandler) System.Delegate.Combine(stocksRowDeletedEvent, value);
				}
				remove
				{
					stocksRowDeletedEvent = (stocksRowChangeEventHandler) System.Delegate.Remove(stocksRowDeletedEvent, value);
				}
			}
			
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void AddstocksRow(stocksRow row)
			{
				this.Rows.Add(row);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public stocksRow AddstocksRow(string item_desc, double available, decimal cost, decimal retail)
			{
				stocksRow rowstocksRow = (stocksRow) (this.NewRow());
				object[] columnValuesArray = new object[] {item_desc, available, cost, retail};
				rowstocksRow.ItemArray = columnValuesArray;
				this.Rows.Add(rowstocksRow);
				return rowstocksRow;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public override global::System.Data.DataTable Clone()
			{
				stocksDataTable cln = (stocksDataTable) (base.Clone());
				cln.InitVars();
				return cln;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Data.DataTable CreateInstance()
			{
				return new stocksDataTable();
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars()
			{
				this.columnitem_desc = base.Columns["item_desc"];
				this.columnavailable = base.Columns["available"];
				this.columncost = base.Columns["cost"];
				this.columnretail = base.Columns["retail"];
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitClass()
			{
				this.columnitem_desc = new global::System.Data.DataColumn("item_desc", typeof(string), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnitem_desc);
				this.columnavailable = new global::System.Data.DataColumn("available", typeof(double), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnavailable);
				this.columncost = new global::System.Data.DataColumn("cost", typeof(decimal), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columncost);
				this.columnretail = new global::System.Data.DataColumn("retail", typeof(decimal), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnretail);
				this.columnitem_desc.AllowDBNull = false;
				this.columnitem_desc.MaxLength = 100;
				this.columncost.AllowDBNull = false;
				this.columnretail.AllowDBNull = false;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public stocksRow NewstocksRow()
			{
				return ((stocksRow) (this.NewRow()));
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder)
			{
				return new stocksRow(builder);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Type GetRowType()
			{
				return typeof(stocksRow);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowChanged(e);
				if (!((this.stocksRowChangedEvent) == null))
				{
					if (stocksRowChangedEvent != null)
						stocksRowChangedEvent(this, new stocksRowChangeEvent(((stocksRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowChanging(e);
				if (!((this.stocksRowChangingEvent) == null))
				{
					if (stocksRowChangingEvent != null)
						stocksRowChangingEvent(this, new stocksRowChangeEvent(((stocksRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowDeleted(e);
				if (!((this.stocksRowDeletedEvent) == null))
				{
					if (stocksRowDeletedEvent != null)
						stocksRowDeletedEvent(this, new stocksRowChangeEvent(((stocksRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowDeleting(e);
				if (!((this.stocksRowDeletingEvent) == null))
				{
					if (stocksRowDeletingEvent != null)
						stocksRowDeletingEvent(this, new stocksRowChangeEvent(((stocksRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void RemovestocksRow(stocksRow row)
			{
				this.Rows.Remove(row);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs)
			{
				global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
				global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
				dsItemCostRetail ds = new dsItemCostRetail();
				global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
				any1.Namespace = "http://www.w3.org/2001/XMLSchema";
				any1.MinOccurs = new decimal(0);
				any1.MaxOccurs = decimal.MaxValue;
				any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
				sequence.Items.Add(any1);
				global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
				any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
				any2.MinOccurs = new decimal(1);
				any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
				sequence.Items.Add(any2);
				global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
				attribute1.Name = "namespace";
				attribute1.FixedValue = ds.Namespace;
				type.Attributes.Add(attribute1);
				global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
				attribute2.Name = "tableTypeName";
				attribute2.FixedValue = "stocksDataTable";
				type.Attributes.Add(attribute2);
				type.Particle = sequence;
				global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
				if (xs.Contains(dsSchema.TargetNamespace))
				{
					global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
					global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
					try
					{
						global::System.Xml.Schema.XmlSchema schema = null;
						dsSchema.Write(s1);
						global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator();
						while (schemas.MoveNext())
						{
							schema = (global::System.Xml.Schema.XmlSchema) schemas.Current;
							s2.SetLength(0);
							schema.Write(s2);
							if (s1.Length == s2.Length)
							{
								s1.Position = 0;
								s2.Position = 0;
								
								while ((s1.Position != s1.Length) 
									&& (s1.ReadByte() == s2.ReadByte()))
								{
									
									
								}
								if (s1.Position == s1.Length)
								{
									return type;
								}
							}
							
						}
					}
					finally
					{
						if (!((s1) == null))
						{
							s1.Close();
						}
						if (!((s2) == null))
						{
							s2.Close();
						}
					}
				}
				xs.Add(dsSchema);
				return type;
			}
		}
		
		///<summary>
		///Represents strongly named DataRow class.
		///</summary>
		public partial class stocksRow : global::System.Data.DataRow
		{
			
			private stocksDataTable tablestocks;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal stocksRow(global::System.Data.DataRowBuilder rb) : base(rb)
			{
				this.tablestocks = (stocksDataTable) this.Table;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public string item_desc
			{
				get
				{
					return System.Convert.ToString(this[this.tablestocks.item_descColumn]);
				}
				set
				{
					this[this.tablestocks.item_descColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public double available
			{
				get
				{
					try
					{
						return System.Convert.ToDouble(this[this.tablestocks.availableColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'available\' in table \'stocks\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tablestocks.availableColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public decimal cost
			{
				get
				{
					return System.Convert.ToDecimal(this[this.tablestocks.costColumn]);
				}
				set
				{
					this[this.tablestocks.costColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public decimal retail
			{
				get
				{
					return System.Convert.ToDecimal(this[this.tablestocks.retailColumn]);
				}
				set
				{
					this[this.tablestocks.retailColumn] = value;
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsavailableNull()
			{
				return this.IsNull(this.tablestocks.availableColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetavailableNull()
			{
				this[this.tablestocks.availableColumn] = global::System.Convert.DBNull;
			}
		}
		
		///<summary>
		///Row event argument class
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public class stocksRowChangeEvent : global::System.EventArgs
		{
			
			private stocksRow eventRow;
			
			private global::System.Data.DataRowAction eventAction;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public stocksRowChangeEvent(stocksRow row, global::System.Data.DataRowAction action)
			{
				this.eventRow = row;
				this.eventAction = action;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public stocksRow Row
			{
				get
				{
					return this.eventRow;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataRowAction Action
			{
				get
				{
					return this.eventAction;
				}
			}
		}
	}
	
	namespace dsItemCostRetailTableAdapters
	{
		
		///<summary>
		///Represents the connection and commands used to retrieve and save data.
		///</summary>
		[global::System.ComponentModel.DesignerCategoryAttribute("code"), 
		global::System.ComponentModel.ToolboxItem(true), 
		global::System.ComponentModel.DataObjectAttribute(true), 
		global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" + 
		", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"), 
		global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]public 
		partial class stocksTableAdapter : global::System.ComponentModel.Component
		{
			
			private global::System.Data.SqlClient.SqlDataAdapter _adapter;
			
			private global::System.Data.SqlClient.SqlConnection _connection;
			
			private global::System.Data.SqlClient.SqlTransaction _transaction;
			
			private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
			
			private bool _clearBeforeFill;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public stocksTableAdapter()
			{
				this.ClearBeforeFill = true;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected internal global::System.Data.SqlClient.SqlDataAdapter Adapter
			{
				get
				{
					if (this._adapter == null)
					{
						this.InitAdapter();
					}
					return this._adapter;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal global::System.Data.SqlClient.SqlConnection Connection
			{
				get
				{
					if (this._connection == null)
					{
						this.InitConnection();
					}
					return this._connection;
				}
				set
				{
					this._connection = value;
					if (!((this.Adapter.InsertCommand) == null))
					{
						this.Adapter.InsertCommand.Connection = value;
					}
					if (!((this.Adapter.DeleteCommand) == null))
					{
						this.Adapter.DeleteCommand.Connection = value;
					}
					if (!((this.Adapter.UpdateCommand) == null))
					{
						this.Adapter.UpdateCommand.Connection = value;
					}
					int i = 0;
					while (i < this.CommandCollection.Length)
					{
						if (!((this.CommandCollection[i]) == null))
						{
							((global::System.Data.SqlClient.SqlCommand) (this.CommandCollection[i])).Connection = value;
						}
						i = i + 1;
					}
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal global::System.Data.SqlClient.SqlTransaction Transaction
			{
				get
				{
					return this._transaction;
				}
				set
				{
					this._transaction = value;
					int i = 0;
					while (i < this.CommandCollection.Length)
					{
						this.CommandCollection[i].Transaction = this._transaction;
						i = i + 1;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.DeleteCommand) == null)))
					{
						this.Adapter.DeleteCommand.Transaction = this._transaction;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.InsertCommand) == null)))
					{
						this.Adapter.InsertCommand.Transaction = this._transaction;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.UpdateCommand) == null)))
					{
						this.Adapter.UpdateCommand.Transaction = this._transaction;
					}
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected global::System.Data.SqlClient.SqlCommand[] CommandCollection
			{
				get
				{
					if (this._commandCollection == null)
					{
						this.InitCommandCollection();
					}
					return this._commandCollection;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool ClearBeforeFill
			{
				get
				{
					return this._clearBeforeFill;
				}
				set
				{
					this._clearBeforeFill = value;
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitAdapter()
			{
				this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
				global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
				tableMapping.SourceTable = "Table";
				tableMapping.DataSetTable = "stocks";
				tableMapping.ColumnMappings.Add("item_desc", "item_desc");
				tableMapping.ColumnMappings.Add("available", "available");
				tableMapping.ColumnMappings.Add("cost", "cost");
				tableMapping.ColumnMappings.Add("retail", "retail");
				this._adapter.TableMappings.Add(tableMapping);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitConnection()
			{
				this._connection = new global::System.Data.SqlClient.SqlConnection();
				this._connection.ConnectionString = global::DoorsPOS.WinApp.My.Settings.Default.doorsposConnectionString;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitCommandCollection()
			{
				this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
				this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
				this._commandCollection[0].Connection = this.Connection;
				this._commandCollection[0].CommandText = "SELECT item_desc, available, cost, retail FROM dbo.stocks";
				this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
			global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"), 
			global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]public virtual int Fill(dsItemCostRetail.stocksDataTable dataTable)
			{
				this.Adapter.SelectCommand = this.CommandCollection[0];
				if (this.ClearBeforeFill == true)
				{
					dataTable.Clear();
				}
				int returnValue = this.Adapter.Fill(dataTable);
				return returnValue;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
			global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"), 
			global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]public virtual dsItemCostRetail.stocksDataTable GetData()
			{
				this.Adapter.SelectCommand = this.CommandCollection[0];
				dsItemCostRetail.stocksDataTable dataTable = new dsItemCostRetail.stocksDataTable();
				this.Adapter.Fill(dataTable);
				return dataTable;
			}
		}
		
		///<summary>
		///TableAdapterManager is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios
		///</summary>
		[global::System.ComponentModel.DesignerCategoryAttribute("code"), 
		global::System.ComponentModel.ToolboxItem(true), 
		global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterManagerDesigner, Microsoft.VSD" + 
		"esigner, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"), 
		global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapterManager")]public 
		partial class TableAdapterManager : global::System.ComponentModel.Component
		{
			
			private UpdateOrderOption _updateOrder;
			
			private bool _backupDataSetBeforeUpdate;
			
			private global::System.Data.IDbConnection _connection;
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public UpdateOrderOption UpdateOrder
			{
				get
				{
					return this._updateOrder;
				}
				set
				{
					this._updateOrder = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool BackupDataSetBeforeUpdate
			{
				get
				{
					return this._backupDataSetBeforeUpdate;
				}
				set
				{
					this._backupDataSetBeforeUpdate = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public global::System.Data.IDbConnection Connection
			{
				get
				{
					if (!((this._connection) == null))
					{
						return this._connection;
					}
					return null;
				}
				set
				{
					this._connection = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public int TableAdapterInstanceCount
			{
				get
				{
					int count = 0;
					return count;
				}
			}
			
			///<summary>
			///Update rows in top-down order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateUpdatedRows(dsItemCostRetail dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Insert rows in top-down order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateInsertedRows(dsItemCostRetail dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Delete rows in bottom-up order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateDeletedRows(dsItemCostRetail dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Remove inserted rows that become updated rows after calling TableAdapter.Update(inserted rows) first
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private global::System.Data.DataRow[] GetRealUpdatedRows(global::System.Data.DataRow[] updatedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				if ((updatedRows == null) 
					|| (updatedRows.Length < 1))
				{
					return updatedRows;
				}
				if ((allAddedRows == null) 
					|| (allAddedRows.Count < 1))
				{
					return updatedRows;
				}
				global::System.Collections.Generic.List<global::System.Data.DataRow> realUpdatedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				int i = 0;
				while (i < updatedRows.Length)
				{
					global::System.Data.DataRow row = updatedRows[i];
					if (allAddedRows.Contains(row) == false)
					{
						realUpdatedRows.Add(row);
					}
					i = i + 1;
				}
				return realUpdatedRows.ToArray();
			}
			
			///<summary>
			///Update all changes to the dataset.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public virtual int UpdateAll(dsItemCostRetail dataSet)
			{
				if (dataSet == null)
				{
					throw (new global::System.ArgumentNullException("dataSet"));
				}
				if (dataSet.HasChanges() == false)
				{
					return 0;
				}
				global::System.Data.IDbConnection workConnection = this.Connection;
				if (workConnection == null)
				{
					throw (new global::System.ApplicationException("TableAdapterManager contains no connection information. Set each TableAdapterMana" + 
						"ger TableAdapter property to a valid TableAdapter instance."));
				}
				bool workConnOpened = false;
				if (System.Convert.ToInt32((workConnection.State & global::System.Data.ConnectionState.Broken)) 
					== (int) global::System.Data.ConnectionState.Broken )
				{
					workConnection.Close();
				}
				if (workConnection.State == global::System.Data.ConnectionState.Closed)
				{
					workConnection.Open();
					workConnOpened = true;
				}
				global::System.Data.IDbTransaction workTransaction = workConnection.BeginTransaction();
				if (workTransaction == null)
				{
					throw (new global::System.ApplicationException("The transaction cannot begin. The current data connection does not support transa" + 
						"ctions or the current state is not allowing the transaction to begin."));
				}
				global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter> adaptersWithAcceptChangesDuringUpdate = new global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter>();
				global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection> revertConnections = new global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection>();
				int result = 0;
				global::System.Data.DataSet backupDataSet = null;
				if (this.BackupDataSetBeforeUpdate)
				{
					backupDataSet = new global::System.Data.DataSet();
					backupDataSet.Merge(dataSet);
				}
				try
				{
					//---- Prepare for update -----------
					//
					//
					//---- Perform updates -----------
					//
					if (this.UpdateOrder == UpdateOrderOption.UpdateInsertDelete)
					{
						result = result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows);
						result = result + this.UpdateInsertedRows(dataSet, allAddedRows);
					}
					else
					{
						result = result + this.UpdateInsertedRows(dataSet, allAddedRows);
						result = result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows);
					}
					result = result + this.UpdateDeletedRows(dataSet, allChangedRows);
					//
					//---- Commit updates -----------
					//
					workTransaction.Commit();
					if (0 < allAddedRows.Count)
					{
						global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allAddedRows.Count) - 1 + 1];
						allAddedRows.CopyTo(rows);
						int i = 0;
						while (i < rows.Length)
						{
							global::System.Data.DataRow row = rows[i];
							row.AcceptChanges();
							i = i + 1;
						}
					}
					if (0 < allChangedRows.Count)
					{
						global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allChangedRows.Count) - 1 + 1];
						allChangedRows.CopyTo(rows);
						int i = 0;
						while (i < rows.Length)
						{
							global::System.Data.DataRow row = rows[i];
							row.AcceptChanges();
							i = i + 1;
						}
					}
				}
				catch (global::System.Exception ex)
				{
					workTransaction.Rollback();
					//---- Restore the dataset -----------
					if (this.BackupDataSetBeforeUpdate)
					{
						global::System.Diagnostics.Debug.Assert(!((backupDataSet) == null));
						dataSet.Clear();
						dataSet.Merge(backupDataSet);
					}
					else
					{
						if (0 < allAddedRows.Count)
						{
							global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allAddedRows.Count) - 1 + 1];
							allAddedRows.CopyTo(rows);
							int i = 0;
							while (i < rows.Length)
							{
								global::System.Data.DataRow row = rows[i];
								row.AcceptChanges();
								row.SetAdded();
								i = i + 1;
							}
						}
					}
					throw (ex);
				}
				finally
				{
					if (workConnOpened)
					{
						workConnection.Close();
					}
					if (0 < adaptersWithAcceptChangesDuringUpdate.Count)
					{
						global::System.Data.Common.DataAdapter[] adapters = new global::System.Data.Common.DataAdapter[(adaptersWithAcceptChangesDuringUpdate.Count) - 1 + 1];
						adaptersWithAcceptChangesDuringUpdate.CopyTo(adapters);
						int i = 0;
						while (i < adapters.Length)
						{
							global::System.Data.Common.DataAdapter adapter = adapters[i];
							adapter.AcceptChangesDuringUpdate = true;
							i = i + 1;
						}
					}
				}
				return result;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected virtual void SortSelfReferenceRows(global::System.Data.DataRow[] rows, global::System.Data.DataRelation relation, bool childFirst)
			{
				global::System.Array.Sort<global::System.Data.DataRow>(rows, new SelfReferenceComparer(relation, childFirst));
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected virtual bool MatchTableAdapterConnection(global::System.Data.IDbConnection inputConnection)
			{
				if (!((this._connection) == null))
				{
					return true;
				}
				if ((this.Connection == null) 
					|| (inputConnection == null))
				{
					return true;
				}
				if (string.Equals(this.Connection.ConnectionString, inputConnection.ConnectionString, global::System.StringComparison.Ordinal))
				{
					return true;
				}
				return false;
			}
			
			///<summary>
			///Update Order Option
			///</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public enum UpdateOrderOption
			{
				
				InsertUpdateDelete = 0,
				
				UpdateInsertDelete = 1
			}
			
			///<summary>
			///Used to sort self-referenced table's rows
			///</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private class SelfReferenceComparer : object, global::System.Collections.Generic.IComparer<global::System.Data.DataRow>
			{
				
				private global::System.Data.DataRelation _relation;
				
				private int _childFirst;
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal SelfReferenceComparer(global::System.Data.DataRelation relation, bool childFirst)
				{
					this._relation = relation;
					if (childFirst)
					{
						this._childFirst = -1;
					}
					else
					{
						this._childFirst = 1;
					}
				}
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private global::System.Data.DataRow GetRoot(global::System.Data.DataRow row, ref int distance)
				{
					global::System.Diagnostics.Debug.Assert(!((row) == null));
					global::System.Data.DataRow root = row;
					distance = 0;
					
					global::System.Collections.Generic.IDictionary<global::System.Data.DataRow, global::System.Data.DataRow> traversedRows = new global::System.Collections.Generic.Dictionary<global::System.Data.DataRow, global::System.Data.DataRow>();
					traversedRows[row] = row;
					
					global::System.Data.DataRow parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
					
					while ((!((parent) == null)) 
						&& (traversedRows.ContainsKey(parent) == false))
					{
						distance = distance + 1;
						root = parent;
						traversedRows[parent] = parent;
						parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
						
					}
					
					if (distance == 0)
					{
						traversedRows.Clear();
						traversedRows[row] = row;
						parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
						
						while ((!((parent) == null)) 
							&& (traversedRows.ContainsKey(parent) == false))
						{
							distance = distance + 1;
							root = parent;
							traversedRows[parent] = parent;
							parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
							
						}
					}
					
					return root;
				}
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int Compare(global::System.Data.DataRow row1, global::System.Data.DataRow row2)
				{
					if (object.ReferenceEquals(row1, row2))
					{
						return 0;
					}
					if (row1 == null)
					{
						return -1;
					}
					if (row2 == null)
					{
						return 1;
					}
					
					int distance1 = 0;
					global::System.Data.DataRow root1 = this.GetRoot(row1, ref distance1);
					
					int distance2 = 0;
					global::System.Data.DataRow root2 = this.GetRoot(row2, ref distance2);
					
					if (object.ReferenceEquals(root1, root2))
					{
						return (this._childFirst * distance1.CompareTo(distance2));
					}
					else
					{
						global::System.Diagnostics.Debug.Assert((!((root1.Table) == null)) 
							&& (!((root2.Table) == null)));
						if (root1.Table.Rows.IndexOf(root1) < root2.Table.Rows.IndexOf(root2))
						{
							return -1;
						}
						else
						{
							return 1;
						}
					}
				}
			}
		}
	}
	
}
