// VBConversions Note: VB project level imports
using System.Data;
using System.Collections.Generic;
using PDSA.Data;
using PDSA.WinForms.Forms;
using PDSA.Security;
using System.Diagnostics;
using PDSA.Common;
using PDSA.WinForms;
using PDSA.WinForms.Security;
using PDSA.PDSACryptography;
using DoorsPOS.Utility;
using Microsoft.VisualBasic;
using System.Collections;
using System;
using DoorsPOS.BusinessLayer;
using System.Windows.Forms;
using System.Drawing;
using System.Linq;
using DoorsPOS.DataLayer;
// End of VB project level imports


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




///<summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
namespace DoorsPOS.WinApp
{
	[global::System.Serializable(), 
	global::System.ComponentModel.DesignerCategoryAttribute("code"), 
	global::System.ComponentModel.ToolboxItem(true), 
	global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"), 
	global::System.Xml.Serialization.XmlRootAttribute("dsPDC"), 
	global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]public 
	partial class dsPDC : global::System.Data.DataSet
	{
		
		private dlvry_hdrDataTable tabledlvry_hdr;
		
		private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dsPDC()
		{
			this.BeginInit();
			this.InitClass();
			global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			base.Tables.CollectionChanged += schemaChangedHandler;
			base.Relations.CollectionChanged += schemaChangedHandler;
			this.EndInit();
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected dsPDC(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : base(info, context, false)
		{
			if (this.IsBinarySerialized(info, context) == true)
			{
				this.InitVars(false);
				global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
				this.Tables.CollectionChanged += schemaChangedHandler1;
				this.Relations.CollectionChanged += schemaChangedHandler1;
				return ;
			}
			string strSchema = System.Convert.ToString(info.GetValue("XmlSchema", typeof(string)));
			if (this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)
			{
				global::System.Data.DataSet ds = new global::System.Data.DataSet();
				ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
				if (!((ds.Tables["dlvry_hdr"]) == null))
				{
					base.Tables.Add(new dlvry_hdrDataTable(ds.Tables["dlvry_hdr"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else
			{
				this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
			}
			this.GetSerializationData(info, context);
			global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			base.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false), 
global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]public dlvry_hdrDataTable dlvry_hdr
		{
			get
			{
				return this.tabledlvry_hdr;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.BrowsableAttribute(true), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]public override global::System.Data.SchemaSerializationMode SchemaSerializationMode
		{
			get
			{
				return this._schemaSerializationMode;
			}
			set
			{
				this._schemaSerializationMode = value;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]public new global::System.Data.DataTableCollection Tables
		{
			get
			{
				return base.Tables;
			}
		}
		
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]public new global::System.Data.DataRelationCollection Relations
		{
			get
			{
				return base.Relations;
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void InitializeDerivedDataSet()
		{
			this.BeginInit();
			this.InitClass();
			this.EndInit();
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public override global::System.Data.DataSet Clone()
		{
			dsPDC cln = (dsPDC) (base.Clone());
			cln.InitVars();
			cln.SchemaSerializationMode = this.SchemaSerializationMode;
			return cln;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override bool ShouldSerializeTables()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override bool ShouldSerializeRelations()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader)
		{
			if (this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)
			{
				this.Reset();
				global::System.Data.DataSet ds = new global::System.Data.DataSet();
				ds.ReadXml(reader);
				if (!((ds.Tables["dlvry_hdr"]) == null))
				{
					base.Tables.Add(new dlvry_hdrDataTable(ds.Tables["dlvry_hdr"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else
			{
				this.ReadXml(reader);
				this.InitVars();
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable()
		{
			global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
			this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
			stream.Position = 0;
			return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars()
		{
			this.InitVars(true);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars(bool initTable)
		{
			this.tabledlvry_hdr = (dlvry_hdrDataTable) (base.Tables["dlvry_hdr"]);
			if (initTable == true)
			{
				if (!((this.tabledlvry_hdr) == null))
				{
					this.tabledlvry_hdr.InitVars();
				}
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitClass()
		{
			this.DataSetName = "dsPDC";
			this.Prefix = "";
			this.Namespace = "http://tempuri.org/dsPDC.xsd";
			this.EnforceConstraints = true;
			this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
			this.tabledlvry_hdr = new dlvry_hdrDataTable();
			base.Tables.Add(this.tabledlvry_hdr);
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private bool ShouldSerializedlvry_hdr()
		{
			return false;
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e)
		{
			if (e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)
			{
				this.InitVars();
			}
		}
		
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs)
		{
			dsPDC ds = new dsPDC();
			global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
			global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
			global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
			any.Namespace = ds.Namespace;
			sequence.Items.Add(any);
			type.Particle = sequence;
			global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
			if (xs.Contains(dsSchema.TargetNamespace))
			{
				global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
				global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
				try
				{
					global::System.Xml.Schema.XmlSchema schema = null;
					dsSchema.Write(s1);
					global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator();
					while (schemas.MoveNext())
					{
						schema = (global::System.Xml.Schema.XmlSchema) schemas.Current;
						s2.SetLength(0);
						schema.Write(s2);
						if (s1.Length == s2.Length)
						{
							s1.Position = 0;
							s2.Position = 0;
							
							while ((s1.Position != s1.Length) 
								&& (s1.ReadByte() == s2.ReadByte()))
							{
								
								
							}
							if (s1.Position == s1.Length)
							{
								return type;
							}
						}
						
					}
				}
				finally
				{
					if (!((s1) == null))
					{
						s1.Close();
					}
					if (!((s2) == null))
					{
						s2.Close();
					}
				}
			}
			xs.Add(dsSchema);
			return type;
		}
		
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public delegate void dlvry_hdrRowChangeEventHandler(object sender, dlvry_hdrRowChangeEvent e);
		
		///<summary>
		///Represents the strongly named DataTable class.
		///</summary>
		[global::System.Serializable(), 
		global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]public 
		partial class dlvry_hdrDataTable : global::System.Data.TypedTableBase<dlvry_hdrRow>
		{
			
			private global::System.Data.DataColumn columndrid;
			
			private global::System.Data.DataColumn columndrdate;
			
			private global::System.Data.DataColumn columndrinv;
			
			private global::System.Data.DataColumn columnsupcode;
			
			private global::System.Data.DataColumn columnterms;
			
			private global::System.Data.DataColumn columndrdue;
			
			private global::System.Data.DataColumn columndrbal;
			
			private global::System.Data.DataColumn columnpaid;
			
			private global::System.Data.DataColumn columndrpsted;
			
			private global::System.Data.DataColumn columnttype;
			
			private global::System.Data.DataColumn columnsupplier;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dlvry_hdrDataTable()
			{
				this.TableName = "dlvry_hdr";
				this.BeginInit()();
				this.InitClass();
				this.EndInit()();
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal dlvry_hdrDataTable(global::System.Data.DataTable table)
			{
				this.TableName = table.TableName;
				if (table.CaseSensitive != table.DataSet.CaseSensitive)
				{
					this.CaseSensitive = table.CaseSensitive;
				}
				if (table.Locale.ToString() != table.DataSet.Locale.ToString())
				{
					this.Locale = table.Locale;
				}
				if (table.Namespace != table.DataSet.Namespace)
				{
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected dlvry_hdrDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : base(info, context)
			{
				this.InitVars();
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn dridColumn
			{
				get
				{
					return this.columndrid;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn drdateColumn
			{
				get
				{
					return this.columndrdate;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn drinvColumn
			{
				get
				{
					return this.columndrinv;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn supcodeColumn
			{
				get
				{
					return this.columnsupcode;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn termsColumn
			{
				get
				{
					return this.columnterms;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn drdueColumn
			{
				get
				{
					return this.columndrdue;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn drbalColumn
			{
				get
				{
					return this.columndrbal;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn paidColumn
			{
				get
				{
					return this.columnpaid;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn drpstedColumn
			{
				get
				{
					return this.columndrpsted;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn ttypeColumn
			{
				get
				{
					return this.columnttype;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataColumn supplierColumn
			{
				get
				{
					return this.columnsupplier;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public int Count
			{
				get
				{
					return this.Rows.Count;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dlvry_hdrRow this[int index]
			{
				get
				{
					return ((dlvry_hdrRow) (this.Rows[index]));
				}
			}
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private dlvry_hdrRowChangeEventHandler dlvry_hdrRowChangingEvent;
			public event dlvry_hdrRowChangeEventHandler dlvry_hdrRowChanging
			{
				add
				{
					dlvry_hdrRowChangingEvent = (dlvry_hdrRowChangeEventHandler) System.Delegate.Combine(dlvry_hdrRowChangingEvent, value);
				}
				remove
				{
					dlvry_hdrRowChangingEvent = (dlvry_hdrRowChangeEventHandler) System.Delegate.Remove(dlvry_hdrRowChangingEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private dlvry_hdrRowChangeEventHandler dlvry_hdrRowChangedEvent;
			public event dlvry_hdrRowChangeEventHandler dlvry_hdrRowChanged
			{
				add
				{
					dlvry_hdrRowChangedEvent = (dlvry_hdrRowChangeEventHandler) System.Delegate.Combine(dlvry_hdrRowChangedEvent, value);
				}
				remove
				{
					dlvry_hdrRowChangedEvent = (dlvry_hdrRowChangeEventHandler) System.Delegate.Remove(dlvry_hdrRowChangedEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private dlvry_hdrRowChangeEventHandler dlvry_hdrRowDeletingEvent;
			public event dlvry_hdrRowChangeEventHandler dlvry_hdrRowDeleting
			{
				add
				{
					dlvry_hdrRowDeletingEvent = (dlvry_hdrRowChangeEventHandler) System.Delegate.Combine(dlvry_hdrRowDeletingEvent, value);
				}
				remove
				{
					dlvry_hdrRowDeletingEvent = (dlvry_hdrRowChangeEventHandler) System.Delegate.Remove(dlvry_hdrRowDeletingEvent, value);
				}
			}
			
			
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private dlvry_hdrRowChangeEventHandler dlvry_hdrRowDeletedEvent;
			public event dlvry_hdrRowChangeEventHandler dlvry_hdrRowDeleted
			{
				add
				{
					dlvry_hdrRowDeletedEvent = (dlvry_hdrRowChangeEventHandler) System.Delegate.Combine(dlvry_hdrRowDeletedEvent, value);
				}
				remove
				{
					dlvry_hdrRowDeletedEvent = (dlvry_hdrRowChangeEventHandler) System.Delegate.Remove(dlvry_hdrRowDeletedEvent, value);
				}
			}
			
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void Adddlvry_hdrRow(dlvry_hdrRow row)
			{
				this.Rows.Add(row);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dlvry_hdrRow Adddlvry_hdrRow(DateTime drdate, string drinv, int supcode, decimal terms, DateTime drdue, decimal drbal, bool paid, bool drpsted, string ttype, string supplier)
			{
				dlvry_hdrRow rowdlvry_hdrRow = (dlvry_hdrRow) (this.NewRow());
				object[] columnValuesArray = new object[] {null, drdate, drinv, supcode, terms, drdue, drbal, paid, drpsted, ttype, supplier};
				rowdlvry_hdrRow.ItemArray = columnValuesArray;
				this.Rows.Add(rowdlvry_hdrRow);
				return rowdlvry_hdrRow;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dlvry_hdrRow FindBydrid(int drid)
			{
				return ((dlvry_hdrRow) (this.Rows.Find(new object[] {drid})));
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public override global::System.Data.DataTable Clone()
			{
				dlvry_hdrDataTable cln = (dlvry_hdrDataTable) (base.Clone());
				cln.InitVars();
				return cln;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Data.DataTable CreateInstance()
			{
				return new dlvry_hdrDataTable();
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal void InitVars()
			{
				this.columndrid = base.Columns["drid"];
				this.columndrdate = base.Columns["drdate"];
				this.columndrinv = base.Columns["drinv"];
				this.columnsupcode = base.Columns["supcode"];
				this.columnterms = base.Columns["terms"];
				this.columndrdue = base.Columns["drdue"];
				this.columndrbal = base.Columns["drbal"];
				this.columnpaid = base.Columns["paid"];
				this.columndrpsted = base.Columns["drpsted"];
				this.columnttype = base.Columns["ttype"];
				this.columnsupplier = base.Columns["supplier"];
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitClass()
			{
				this.columndrid = new global::System.Data.DataColumn("drid", typeof(int), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrid);
				this.columndrdate = new global::System.Data.DataColumn("drdate", typeof(DateTime), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrdate);
				this.columndrinv = new global::System.Data.DataColumn("drinv", typeof(string), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrinv);
				this.columnsupcode = new global::System.Data.DataColumn("supcode", typeof(int), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnsupcode);
				this.columnterms = new global::System.Data.DataColumn("terms", typeof(decimal), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnterms);
				this.columndrdue = new global::System.Data.DataColumn("drdue", typeof(DateTime), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrdue);
				this.columndrbal = new global::System.Data.DataColumn("drbal", typeof(decimal), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrbal);
				this.columnpaid = new global::System.Data.DataColumn("paid", typeof(bool), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnpaid);
				this.columndrpsted = new global::System.Data.DataColumn("drpsted", typeof(bool), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columndrpsted);
				this.columnttype = new global::System.Data.DataColumn("ttype", typeof(string), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnttype);
				this.columnsupplier = new global::System.Data.DataColumn("supplier", typeof(string), null, global::System.Data.MappingType.Element);
				base.Columns.Add(this.columnsupplier);
				this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {this.columndrid}, true));
				this.columndrid.AutoIncrement = true;
				this.columndrid.AutoIncrementSeed = -1;
				this.columndrid.AutoIncrementStep = -1;
				this.columndrid.AllowDBNull = false;
				this.columndrid.ReadOnly = true;
				this.columndrid.Unique = true;
				this.columndrdate.AllowDBNull = false;
				this.columndrinv.AllowDBNull = false;
				this.columndrinv.MaxLength = 15;
				this.columnttype.MaxLength = 25;
				this.columnsupplier.AllowDBNull = false;
				this.columnsupplier.MaxLength = 50;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dlvry_hdrRow Newdlvry_hdrRow()
			{
				return ((dlvry_hdrRow) (this.NewRow()));
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder)
			{
				return new dlvry_hdrRow(builder);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override global::System.Type GetRowType()
			{
				return typeof(dlvry_hdrRow);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowChanged(e);
				if (!((this.dlvry_hdrRowChangedEvent) == null))
				{
					if (dlvry_hdrRowChangedEvent != null)
						dlvry_hdrRowChangedEvent(this, new dlvry_hdrRowChangeEvent(((dlvry_hdrRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowChanging(e);
				if (!((this.dlvry_hdrRowChangingEvent) == null))
				{
					if (dlvry_hdrRowChangingEvent != null)
						dlvry_hdrRowChangingEvent(this, new dlvry_hdrRowChangeEvent(((dlvry_hdrRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowDeleted(e);
				if (!((this.dlvry_hdrRowDeletedEvent) == null))
				{
					if (dlvry_hdrRowDeletedEvent != null)
						dlvry_hdrRowDeletedEvent(this, new dlvry_hdrRowChangeEvent(((dlvry_hdrRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e)
			{
				base.OnRowDeleting(e);
				if (!((this.dlvry_hdrRowDeletingEvent) == null))
				{
					if (dlvry_hdrRowDeletingEvent != null)
						dlvry_hdrRowDeletingEvent(this, new dlvry_hdrRowChangeEvent(((dlvry_hdrRow) e.Row), e.Action));
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void Removedlvry_hdrRow(dlvry_hdrRow row)
			{
				this.Rows.Remove(row);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs)
			{
				global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
				global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
				dsPDC ds = new dsPDC();
				global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
				any1.Namespace = "http://www.w3.org/2001/XMLSchema";
				any1.MinOccurs = new decimal(0);
				any1.MaxOccurs = decimal.MaxValue;
				any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
				sequence.Items.Add(any1);
				global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
				any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
				any2.MinOccurs = new decimal(1);
				any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
				sequence.Items.Add(any2);
				global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
				attribute1.Name = "namespace";
				attribute1.FixedValue = ds.Namespace;
				type.Attributes.Add(attribute1);
				global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
				attribute2.Name = "tableTypeName";
				attribute2.FixedValue = "dlvry_hdrDataTable";
				type.Attributes.Add(attribute2);
				type.Particle = sequence;
				global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
				if (xs.Contains(dsSchema.TargetNamespace))
				{
					global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
					global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
					try
					{
						global::System.Xml.Schema.XmlSchema schema = null;
						dsSchema.Write(s1);
						global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator();
						while (schemas.MoveNext())
						{
							schema = (global::System.Xml.Schema.XmlSchema) schemas.Current;
							s2.SetLength(0);
							schema.Write(s2);
							if (s1.Length == s2.Length)
							{
								s1.Position = 0;
								s2.Position = 0;
								
								while ((s1.Position != s1.Length) 
									&& (s1.ReadByte() == s2.ReadByte()))
								{
									
									
								}
								if (s1.Position == s1.Length)
								{
									return type;
								}
							}
							
						}
					}
					finally
					{
						if (!((s1) == null))
						{
							s1.Close();
						}
						if (!((s2) == null))
						{
							s2.Close();
						}
					}
				}
				xs.Add(dsSchema);
				return type;
			}
		}
		
		///<summary>
		///Represents strongly named DataRow class.
		///</summary>
		public partial class dlvry_hdrRow : global::System.Data.DataRow
		{
			
			private dlvry_hdrDataTable tabledlvry_hdr;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal dlvry_hdrRow(global::System.Data.DataRowBuilder rb) : base(rb)
			{
				this.tabledlvry_hdr = (dlvry_hdrDataTable) this.Table;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int drid
			{
				get
				{
					return System.Convert.ToInt32(this[this.tabledlvry_hdr.dridColumn]);
				}
				set
				{
					this[this.tabledlvry_hdr.dridColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public DateTime drdate
			{
				get
				{
					return System.Convert.ToDateTime(this[this.tabledlvry_hdr.drdateColumn]);
				}
				set
				{
					this[this.tabledlvry_hdr.drdateColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public string drinv
			{
				get
				{
					return System.Convert.ToString(this[this.tabledlvry_hdr.drinvColumn]);
				}
				set
				{
					this[this.tabledlvry_hdr.drinvColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int supcode
			{
				get
				{
					try
					{
						return System.Convert.ToInt32(this[this.tabledlvry_hdr.supcodeColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'supcode\' in table \'dlvry_hdr\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tabledlvry_hdr.supcodeColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public decimal terms
			{
				get
				{
					try
					{
						return System.Convert.ToDecimal(this[this.tabledlvry_hdr.termsColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'terms\' in table \'dlvry_hdr\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tabledlvry_hdr.termsColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public DateTime drdue
			{
				get
				{
					try
					{
						return System.Convert.ToDateTime(this[this.tabledlvry_hdr.drdueColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'drdue\' in table \'dlvry_hdr\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tabledlvry_hdr.drdueColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public decimal drbal
			{
				get
				{
					try
					{
						return System.Convert.ToDecimal(this[this.tabledlvry_hdr.drbalColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'drbal\' in table \'dlvry_hdr\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tabledlvry_hdr.drbalColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool paid
			{
				get
				{
					try
					{
						return System.Convert.ToBoolean(this[this.tabledlvry_hdr.paidColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'paid\' in table \'dlvry_hdr\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tabledlvry_hdr.paidColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool drpsted
			{
				get
				{
					try
					{
						return System.Convert.ToBoolean(this[this.tabledlvry_hdr.drpstedColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'drpsted\' in table \'dlvry_hdr\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tabledlvry_hdr.drpstedColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public string ttype
			{
				get
				{
					try
					{
						return System.Convert.ToString(this[this.tabledlvry_hdr.ttypeColumn]);
					}
					catch (global::System.InvalidCastException e)
					{
						throw (new global::System.Data.StrongTypingException("The value for column \'ttype\' in table \'dlvry_hdr\' is DBNull.", e));
					}
				}
				set
				{
					this[this.tabledlvry_hdr.ttypeColumn] = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public string supplier
			{
				get
				{
					return System.Convert.ToString(this[this.tabledlvry_hdr.supplierColumn]);
				}
				set
				{
					this[this.tabledlvry_hdr.supplierColumn] = value;
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IssupcodeNull()
			{
				return this.IsNull(this.tabledlvry_hdr.supcodeColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetsupcodeNull()
			{
				this[this.tabledlvry_hdr.supcodeColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IstermsNull()
			{
				return this.IsNull(this.tabledlvry_hdr.termsColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SettermsNull()
			{
				this[this.tabledlvry_hdr.termsColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsdrdueNull()
			{
				return this.IsNull(this.tabledlvry_hdr.drdueColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetdrdueNull()
			{
				this[this.tabledlvry_hdr.drdueColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsdrbalNull()
			{
				return this.IsNull(this.tabledlvry_hdr.drbalColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetdrbalNull()
			{
				this[this.tabledlvry_hdr.drbalColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IspaidNull()
			{
				return this.IsNull(this.tabledlvry_hdr.paidColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetpaidNull()
			{
				this[this.tabledlvry_hdr.paidColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsdrpstedNull()
			{
				return this.IsNull(this.tabledlvry_hdr.drpstedColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetdrpstedNull()
			{
				this[this.tabledlvry_hdr.drpstedColumn] = global::System.Convert.DBNull;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool IsttypeNull()
			{
				return this.IsNull(this.tabledlvry_hdr.ttypeColumn);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public void SetttypeNull()
			{
				this[this.tabledlvry_hdr.ttypeColumn] = global::System.Convert.DBNull;
			}
		}
		
		///<summary>
		///Row event argument class
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public class dlvry_hdrRowChangeEvent : global::System.EventArgs
		{
			
			private dlvry_hdrRow eventRow;
			
			private global::System.Data.DataRowAction eventAction;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dlvry_hdrRowChangeEvent(dlvry_hdrRow row, global::System.Data.DataRowAction action)
			{
				this.eventRow = row;
				this.eventAction = action;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dlvry_hdrRow Row
			{
				get
				{
					return this.eventRow;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public global::System.Data.DataRowAction Action
			{
				get
				{
					return this.eventAction;
				}
			}
		}
	}
	
	namespace dsPDCTableAdapters
	{
		
		///<summary>
		///Represents the connection and commands used to retrieve and save data.
		///</summary>
		[global::System.ComponentModel.DesignerCategoryAttribute("code"), 
		global::System.ComponentModel.ToolboxItem(true), 
		global::System.ComponentModel.DataObjectAttribute(true), 
		global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" + 
		", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"), 
		global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]public 
		partial class dlvry_hdrTableAdapter : global::System.ComponentModel.Component
		{
			
			private global::System.Data.SqlClient.SqlDataAdapter _adapter;
			
			private global::System.Data.SqlClient.SqlConnection _connection;
			
			private global::System.Data.SqlClient.SqlTransaction _transaction;
			
			private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
			
			private bool _clearBeforeFill;
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public dlvry_hdrTableAdapter()
			{
				this.ClearBeforeFill = true;
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected internal global::System.Data.SqlClient.SqlDataAdapter Adapter
			{
				get
				{
					if (this._adapter == null)
					{
						this.InitAdapter();
					}
					return this._adapter;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal global::System.Data.SqlClient.SqlConnection Connection
			{
				get
				{
					if (this._connection == null)
					{
						this.InitConnection();
					}
					return this._connection;
				}
				set
				{
					this._connection = value;
					if (!((this.Adapter.InsertCommand) == null))
					{
						this.Adapter.InsertCommand.Connection = value;
					}
					if (!((this.Adapter.DeleteCommand) == null))
					{
						this.Adapter.DeleteCommand.Connection = value;
					}
					if (!((this.Adapter.UpdateCommand) == null))
					{
						this.Adapter.UpdateCommand.Connection = value;
					}
					int i = 0;
					while (i < this.CommandCollection.Length)
					{
						if (!((this.CommandCollection[i]) == null))
						{
							((global::System.Data.SqlClient.SqlCommand) (this.CommandCollection[i])).Connection = value;
						}
						i = i + 1;
					}
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal global::System.Data.SqlClient.SqlTransaction Transaction
			{
				get
				{
					return this._transaction;
				}
				set
				{
					this._transaction = value;
					int i = 0;
					while (i < this.CommandCollection.Length)
					{
						this.CommandCollection[i].Transaction = this._transaction;
						i = i + 1;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.DeleteCommand) == null)))
					{
						this.Adapter.DeleteCommand.Transaction = this._transaction;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.InsertCommand) == null)))
					{
						this.Adapter.InsertCommand.Transaction = this._transaction;
					}
					if ((!((this.Adapter) == null)) 
						&& (!((this.Adapter.UpdateCommand) == null)))
					{
						this.Adapter.UpdateCommand.Transaction = this._transaction;
					}
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected global::System.Data.SqlClient.SqlCommand[] CommandCollection
			{
				get
				{
					if (this._commandCollection == null)
					{
						this.InitCommandCollection();
					}
					return this._commandCollection;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool ClearBeforeFill
			{
				get
				{
					return this._clearBeforeFill;
				}
				set
				{
					this._clearBeforeFill = value;
				}
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitAdapter()
			{
				this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
				global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
				tableMapping.SourceTable = "Table";
				tableMapping.DataSetTable = "dlvry_hdr";
				tableMapping.ColumnMappings.Add("drid", "drid");
				tableMapping.ColumnMappings.Add("drdate", "drdate");
				tableMapping.ColumnMappings.Add("drinv", "drinv");
				tableMapping.ColumnMappings.Add("supcode", "supcode");
				tableMapping.ColumnMappings.Add("terms", "terms");
				tableMapping.ColumnMappings.Add("drdue", "drdue");
				tableMapping.ColumnMappings.Add("drbal", "drbal");
				tableMapping.ColumnMappings.Add("paid", "paid");
				tableMapping.ColumnMappings.Add("drpsted", "drpsted");
				tableMapping.ColumnMappings.Add("ttype", "ttype");
				tableMapping.ColumnMappings.Add("supplier", "supplier");
				this._adapter.TableMappings.Add(tableMapping);
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitConnection()
			{
				this._connection = new global::System.Data.SqlClient.SqlConnection();
				this._connection.ConnectionString = global::DoorsPOS.WinApp.My.Settings.Default.doorsposConnectionString;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private void InitCommandCollection()
			{
				this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
				this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
				this._commandCollection[0].Connection = this.Connection;
				this._commandCollection[0].CommandText = "SELECT     dlvry_hdr.drid, dlvry_hdr.drdate, dlvry_hdr.drinv, dlvry_hdr.supcode, " + 
					"dlvry_hdr.terms, dlvry_hdr.drdue, dlvry_hdr.drbal, dlvry_hdr.paid, dlvry_hdr.drp" + 
					"sted, " + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(13)) + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(10)) + "                      dlvry_hdr.ttype, suppliers.supplier" + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(13)) + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(10)) + "FROM         " + 
					"dlvry_hdr INNER JOIN" + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(13)) + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(10)) + "                      suppliers ON dlvry_hdr.supcode = sup" + 
					"pliers.supcode" + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(13)) + System.Convert.ToString(global::Microsoft.VisualBasic.Strings.ChrW(10)) + "WHERE dlvry_hdr.drdue>=GETDATE() AND dlvry_hdr.drpsted=0";
				this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
			global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"), 
			global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]public virtual int Fill(dsPDC.dlvry_hdrDataTable dataTable)
			{
				this.Adapter.SelectCommand = this.CommandCollection[0];
				if (this.ClearBeforeFill == true)
				{
					dataTable.Clear();
				}
				int returnValue = this.Adapter.Fill(dataTable);
				return returnValue;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
			global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"), 
			global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]public virtual dsPDC.dlvry_hdrDataTable GetData()
			{
				this.Adapter.SelectCommand = this.CommandCollection[0];
				dsPDC.dlvry_hdrDataTable dataTable = new dsPDC.dlvry_hdrDataTable();
				this.Adapter.Fill(dataTable);
				return dataTable;
			}
		}
		
		///<summary>
		///TableAdapterManager is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios
		///</summary>
		[global::System.ComponentModel.DesignerCategoryAttribute("code"), 
		global::System.ComponentModel.ToolboxItem(true), 
		global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterManagerDesigner, Microsoft.VSD" + 
		"esigner, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"), 
		global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapterManager")]public 
		partial class TableAdapterManager : global::System.ComponentModel.Component
		{
			
			private UpdateOrderOption _updateOrder;
			
			private bool _backupDataSetBeforeUpdate;
			
			private global::System.Data.IDbConnection _connection;
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public UpdateOrderOption UpdateOrder
			{
				get
				{
					return this._updateOrder;
				}
				set
				{
					this._updateOrder = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public bool BackupDataSetBeforeUpdate
			{
				get
				{
					return this._backupDataSetBeforeUpdate;
				}
				set
				{
					this._backupDataSetBeforeUpdate = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public global::System.Data.IDbConnection Connection
			{
				get
				{
					if (!((this._connection) == null))
					{
						return this._connection;
					}
					return null;
				}
				set
				{
					this._connection = value;
				}
			}
			
[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), 
global::System.ComponentModel.Browsable(false)]public int TableAdapterInstanceCount
			{
				get
				{
					int count = 0;
					return count;
				}
			}
			
			///<summary>
			///Update rows in top-down order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateUpdatedRows(dsPDC dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Insert rows in top-down order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateInsertedRows(dsPDC dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Delete rows in bottom-up order.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private int UpdateDeletedRows(dsPDC dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows)
			{
				int result = 0;
				return result;
			}
			
			///<summary>
			///Remove inserted rows that become updated rows after calling TableAdapter.Update(inserted rows) first
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private global::System.Data.DataRow[] GetRealUpdatedRows(global::System.Data.DataRow[] updatedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows)
			{
				if ((updatedRows == null) 
					|| (updatedRows.Length < 1))
				{
					return updatedRows;
				}
				if ((allAddedRows == null) 
					|| (allAddedRows.Count < 1))
				{
					return updatedRows;
				}
				global::System.Collections.Generic.List<global::System.Data.DataRow> realUpdatedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				int i = 0;
				while (i < updatedRows.Length)
				{
					global::System.Data.DataRow row = updatedRows[i];
					if (allAddedRows.Contains(row) == false)
					{
						realUpdatedRows.Add(row);
					}
					i = i + 1;
				}
				return realUpdatedRows.ToArray;
			}
			
			///<summary>
			///Update all changes to the dataset.
			///</summary>
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public virtual int UpdateAll(dsPDC dataSet)
			{
				if (dataSet == null)
				{
					throw (new global::System.ArgumentNullException("dataSet"));
				}
				if (dataSet.HasChanges() == false)
				{
					return 0;
				}
				global::System.Data.IDbConnection workConnection = this.Connection;
				if (workConnection == null)
				{
					throw (new global::System.ApplicationException("TableAdapterManager contains no connection information. Set each TableAdapterMana" + 
						"ger TableAdapter property to a valid TableAdapter instance."));
				}
				bool workConnOpened = false;
				if ((workConnection.State & global::System.Data.ConnectionState.Broken) 
					== (int) global::System.Data.ConnectionState.Broken)
				{
					workConnection.Close();
				}
				if (workConnection.State == global::System.Data.ConnectionState.Closed)
				{
					workConnection.Open();
					workConnOpened = true;
				}
				global::System.Data.IDbTransaction workTransaction = workConnection.BeginTransaction();
				if (workTransaction == null)
				{
					throw (new global::System.ApplicationException("The transaction cannot begin. The current data connection does not support transa" + 
						"ctions or the current state is not allowing the transaction to begin."));
				}
				global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
				global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter> adaptersWithAcceptChangesDuringUpdate = new global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter>();
				global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection> revertConnections = new global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection>();
				int result = 0;
				global::System.Data.DataSet backupDataSet = null;
				if (this.BackupDataSetBeforeUpdate)
				{
					backupDataSet = new global::System.Data.DataSet();
					backupDataSet.Merge(dataSet);
				}
				try
				{
					//---- Prepare for update -----------
					//
					//
					//---- Perform updates -----------
					//
					if (this.UpdateOrder == UpdateOrderOption.UpdateInsertDelete)
					{
						result = result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows);
						result = result + this.UpdateInsertedRows(dataSet, allAddedRows);
					}
					else
					{
						result = result + this.UpdateInsertedRows(dataSet, allAddedRows);
						result = result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows);
					}
					result = result + this.UpdateDeletedRows(dataSet, allChangedRows);
					//
					//---- Commit updates -----------
					//
					workTransaction.Commit();
					if (0 < allAddedRows.Count)
					{
						global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allAddedRows.Count) - 1 + 1];
						allAddedRows.CopyTo(rows);
						int i = 0;
						while (i < rows.Length)
						{
							global::System.Data.DataRow row = rows[i];
							row.AcceptChanges();
							i = i + 1;
						}
					}
					if (0 < allChangedRows.Count)
					{
						global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allChangedRows.Count) - 1 + 1];
						allChangedRows.CopyTo(rows);
						int i = 0;
						while (i < rows.Length)
						{
							global::System.Data.DataRow row = rows[i];
							row.AcceptChanges();
							i = i + 1;
						}
					}
				}
				catch (global::System.Exception ex)
				{
					workTransaction.Rollback();
					//---- Restore the dataset -----------
					if (this.BackupDataSetBeforeUpdate)
					{
						global::System.Diagnostics.Debug.Assert(!((backupDataSet) == null));
						dataSet.Clear();
						dataSet.Merge(backupDataSet);
					}
					else
					{
						if (0 < allAddedRows.Count)
						{
							global::System.Data.DataRow[] rows = new global::System.Data.DataRow[(allAddedRows.Count) - 1 + 1];
							allAddedRows.CopyTo(rows);
							int i = 0;
							while (i < rows.Length)
							{
								global::System.Data.DataRow row = rows[i];
								row.AcceptChanges();
								row.SetAdded();
								i = i + 1;
							}
						}
					}
					throw (ex);
				}
				finally
				{
					if (workConnOpened)
					{
						workConnection.Close();
					}
					if (0 < adaptersWithAcceptChangesDuringUpdate.Count)
					{
						global::System.Data.Common.DataAdapter[] adapters = new global::System.Data.Common.DataAdapter[(adaptersWithAcceptChangesDuringUpdate.Count) - 1 + 1];
						adaptersWithAcceptChangesDuringUpdate.CopyTo(adapters);
						int i = 0;
						while (i < adapters.Length)
						{
							global::System.Data.Common.DataAdapter adapter = adapters[i];
							adapter.AcceptChangesDuringUpdate = true;
							i = i + 1;
						}
					}
				}
				return result;
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected virtual void SortSelfReferenceRows(global::System.Data.DataRow[] rows, global::System.Data.DataRelation relation, bool childFirst)
			{
				global::System.Array.Sort<global::System.Data.DataRow>(rows, new SelfReferenceComparer(relation, childFirst));
			}
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
			global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]protected virtual bool MatchTableAdapterConnection(global::System.Data.IDbConnection inputConnection)
			{
				if (!((this._connection) == null))
				{
					return true;
				}
				if ((this.Connection == null) 
					|| (inputConnection == null))
				{
					return true;
				}
				if (string.Equals(this.Connection.ConnectionString, inputConnection.ConnectionString, global::System.StringComparison.Ordinal))
				{
					return true;
				}
				return false;
			}
			
			///<summary>
			///Update Order Option
			///</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public enum UpdateOrderOption
			{
				
				InsertUpdateDelete = 0,
				
				UpdateInsertDelete = 1
			}
			
			///<summary>
			///Used to sort self-referenced table's rows
			///</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private class SelfReferenceComparer : object, global::System.Collections.Generic.IComparer<global::System.Data.DataRow>
			{
				
				private global::System.Data.DataRelation _relation;
				
				private int _childFirst;
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]internal SelfReferenceComparer(global::System.Data.DataRelation relation, bool childFirst)
				{
					this._relation = relation;
					if (childFirst)
					{
						this._childFirst = -1;
					}
					else
					{
						this._childFirst = 1;
					}
				}
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]private global::System.Data.DataRow GetRoot(global::System.Data.DataRow row, ref int distance)
				{
					global::System.Diagnostics.Debug.Assert(!((row) == null));
					global::System.Data.DataRow root = row;
					distance = 0;
					
					global::System.Collections.Generic.IDictionary<global::System.Data.DataRow, global::System.Data.DataRow> traversedRows = new global::System.Collections.Generic.Dictionary<global::System.Data.DataRow, global::System.Data.DataRow>();
					traversedRows[row] = row;
					
					global::System.Data.DataRow parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
					
					while ((!((parent) == null)) 
						&& (traversedRows.ContainsKey(parent) == false))
					{
						distance = distance + 1;
						root = parent;
						traversedRows[parent] = parent;
						parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
						
					}
					
					if (distance == 0)
					{
						traversedRows.Clear();
						traversedRows[row] = row;
						parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
						
						while ((!((parent) == null)) 
							&& (traversedRows.ContainsKey(parent) == false))
						{
							distance = distance + 1;
							root = parent;
							traversedRows[parent] = parent;
							parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
							
						}
					}
					
					return root;
				}
				
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
				global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]public int Compare(global::System.Data.DataRow row1, global::System.Data.DataRow row2)
				{
					if (object.ReferenceEquals(row1, row2))
					{
						return 0;
					}
					if (row1 == null)
					{
						return -1;
					}
					if (row2 == null)
					{
						return 1;
					}
					
					int distance1 = 0;
					global::System.Data.DataRow root1 = this.GetRoot(row1, ref distance1);
					
					int distance2 = 0;
					global::System.Data.DataRow root2 = this.GetRoot(row2, ref distance2);
					
					if (object.ReferenceEquals(root1, root2))
					{
						return (this._childFirst * distance1.CompareTo(distance2));
					}
					else
					{
						global::System.Diagnostics.Debug.Assert((!((root1.Table) == null)) 
							&& (!((root2.Table) == null)));
						if (root1.Table.Rows.IndexOf(root1) < root2.Table.Rows.IndexOf(root2))
						{
							return -1;
						}
						else
						{
							return 1;
						}
					}
				}
			}
		}
	}
	
}
